- README.md
- config/secrets.yml
Removes dev and test secrets - adds intructions
> Make sure all secrets are in env vars

- Gemfile
- Gemfile.lock
- app/models/datafile.rb
- app/models/dataset.rb
- app/models/inspire_dataset.rb
- app/models/location.rb
- app/models/organisation.rb
- app/models/organisation_statistic.rb
- db/migrate/20170531151258_create_organisation_statistics.rb
- db/migrate/20170531152436_create_locations.rb
- db/migrate/20170531152818_create_datasets.rb
- db/migrate/20170531153330_create_inspire_datasets.rb
- db/migrate/20170531154500_create_datafiles.rb
- db/migrate/20170531154736_create_organisations.rb
- db/migrate/20170531155515_organisation_users.rb
- db/schema.rb
These are all the dataset models from the django app, plus one statistics model. The models are there but they are not linked up properly yet i.e. no belongs_to or has_many
> Replicate all main dataset models

- app/assets/javascripts/datasets.coffee
- app/assets/javascripts/manage.coffee
- app/assets/javascripts/tasks.coffee
- app/assets/javascripts/users.coffee
- app/assets/stylesheets/datasets.scss
- app/assets/stylesheets/manage.scss
- app/assets/stylesheets/tasks.scss
- app/assets/stylesheets/users.scss
- app/controllers/datasets_controller.rb
- app/controllers/manage_controller.rb
- app/controllers/tasks_controller.rb
- app/controllers/users_controller.rb
- app/helpers/datasets_helper.rb
- app/helpers/manage_helper.rb
- app/helpers/tasks_helper.rb
- app/helpers/users_helper.rb
- config/routes.rb
Adds datasets, tasks, and users as CRUD controllers, and manage as a custom one with routes for manage_own and manage_org
> Generate controllers and add routes

- .gitignore
- config/database.yml
- end-to-end-tests/common.js
- end-to-end-tests/nightwatch.conf.js
- end-to-end-tests/nightwatch.json
- end-to-end-tests/run_fe_tests.sh
- end-to-end-tests/test-users.json
- end-to-end-tests/tests/create.js
- end-to-end-tests/tests/edit.js
- end-to-end-tests/tests/login.js
add the front-end tests from publish_data_alpha, and adapt them to Rails.
Missing: adding fixtures to populate the test database with datasets, organisations and users
> Front end tests

- Gemfile
- Gemfile.lock
- app/controllers/tasks_controller.rb
- app/models/organisation.rb
- app/models/publishing_user.rb
- config/routes.rb
- db/migrate/20170605093333_create_join_table_publishing_user_organisation.rb
- spec/features/log_in_spec.rb
- spec/rails_helper.rb
- spec/spec_helper.rb
Implements a test that just calls up the index page, for now. Also includes a table migration I missed and some corrections to PublishingUser and Organisation models.
> Very basic integration test

- app/views/home/index.html.erb
- app/views/layouts/application.html.erb
.. by moving it out of the content block.  May want to use a different
layout for homepage (so we don't have to have the main id='content' in
each page) but this works well for now.
> Fix the masthead ..

- app/views/tasks/my.html.erb
- app/views/tasks/organisation.html.erb
> adds main tag to make tasks template look nice again

- app/views/publishing_users/sessions/new.html.erb
- app/views/publishing_users/shared/_links.html.erb
- spec/features/log_in_spec.rb
Fixes the login template to use the govuk styles
> Fix the login template

- app/views/publishing_users/passwords/new.html.erb
- app/views/publishing_users/registrations/new.html.erb
- app/views/publishing_users/unlocks/new.html.erb
- config/routes.rb
Fix all of the 'new' templates for devise so they look govuk-ish.
> Fix the devise templates

- app/controllers/manage_controller.rb
- app/views/manage/_base.html.erb
- app/views/manage/manage_org.html.erb
- app/views/manage/manage_organisation.html.erb
- app/views/manage/manage_own.html.erb
- app/views/manage/shared/_search.html.erb
- config/routes.rb
- spec/features/manage_spec.rb
The controller doesn't yet implement searching, or sorting, and
the links to add/edit don't yet work (we don't have URLs yet).
Would welcome ideas on how to something in the controller so I don't have to repeat the setting of find_url ...
> Adds templates and controller for manage.

- Gemfile
- Gemfile.lock
- app/controllers/manage_controller.rb
- app/views/kaminari/_gap.html.erb
- app/views/kaminari/_page.html.erb
- app/views/kaminari/_paginator.html.erb
- app/views/manage/_base.html.erb
- config/initializers/kaminari_config.rb
- db/seeds.rb
> Manage pagination

- README.md
> #65 Add waffle badge to README

- app/controllers/manage_controller.rb
- app/helpers/manage_helper.rb
- app/models/organisation.rb
- app/views/manage/_base.html.erb
- db/migrate/20170614161633_set_published_default_on_datasets.rb
- db/seeds.rb
- spec/features/manage_spec.rb
- The search function was displaying organisation datasets on the my datasets page if there was a search query entered. This PR fixes it but let me know if there's a better way as it's a bit ugly!
- Have added a test to check for the above
- Sorts on dataset name or publish status
> Manage sort

- app/controllers/datasets_controller.rb
> Set creator_id on new datasets

- app/views/layouts/_staging_ribbon.html.erb
- app/views/layouts/application.html.erb
- config/database.yml
- config/environments/staging.rb
- config/secrets.yml
Adds a corner banner so it's obvious that the heroku shows staging env
> Add 'STAGING' banner on Heroku

- db/migrate/20170619140813_fix_orgs_users_table.rb
- spec/models/user_spec.rb
Rename the publishing_user_id field (to user_id) and add a test
to ensure we can add organisations to a user
Closes #68
> Fix the organisations-users join table

- README.md
> Updates readme to include information on importing data

- .travis.yml
- README.md
Tell travis we don't need sudo, we don't need libxml (already installed) and that it can cache bundler gems
> Speed up travis builds

- app/controllers/datasets_controller.rb
- app/models/dataset.rb
- app/views/datasets/_date_field.html.erb
- app/views/datasets/_month_input.html.erb
- app/views/datasets/_quarter_inputs.html.erb
- app/views/datasets/_year_input.html.erb
- app/views/datasets/addfile.html.erb
- spec/features/datasets_spec.rb
Includes:
* helpers
* form views/partials
* test suite
Solves: #81
> Add dataset frequency calculations in so that start and end dates are calculated

- .codeclimate.yml
- db/seeds.rb
- lib/util/linkchecker.rb
- lib/util/organisation_checker.rb
- lib/util/overduechecker.rb
Tweak some CC config and remove some style issues.
> [DO NOT MERGE] CC Cleanup

- app/controllers/datafiles_controller.rb
- app/models/datafile.rb
- app/views/datafiles/_date_field.html.erb
- app/views/datafiles/_month_input.html.erb
- app/views/datafiles/_quarter_inputs.html.erb
- app/views/datafiles/_year_input.html.erb
- app/views/datasets/show.html.erb
- spec/features/datasets_spec.rb
When a datafile is being edited, it should show any existing dates that have been entered. This change adds that, as well as fixing a display bug.
> Fix Datafile form prefill

- app/controllers/datasets_controller.rb
- app/helpers/manage_helper.rb
- app/views/manage/_base.html.erb
- app/views/manage/manage_own.html.erb
- spec/features/datasets_spec.rb
Adds a flash message on publish,also links to the dataset in FIND.
Fixes #149
> Add flash message on publish

- app/controllers/datafiles_controller.rb
- app/models/datafile.rb
- spec/features/datasets_spec.rb
Other fixes:
* Error when no date is entered #128 
* Bad dates make application crash #161 
* Move methods to model #143 
* Validation flashes #159 & #151 (& #117?)
> Datafile date validation

- app/views/datasets/publish.html.erb
- app/views/manage/_base.html.erb
- db/seeds.rb
* Cleans up dataset names in seeds to avoid spaces
* Makes edit link go to publish
* Allows you to republish a published dataset (will need content change)
> Fixes some slightly broken publish/manage issues.

- app/controllers/datasets_controller.rb
- app/models/dataset.rb
- app/views/datasets/show.html.erb
> Show errors on publish page

- app/controllers/datafiles_controller.rb
- app/models/datafile.rb
- app/views/datafiles/new.html.erb
- app/views/datafiles/new_doc.html.erb
> Ensure that routing around files/docs is correct

- app/controllers/tasks_controller.rb
- app/helpers/tasks_helper.rb
- app/views/tasks/_base.html.erb
- lib/util/linkchecker.rb
- lib/util/organisation_checker.rb
- spec/features/tasks_spec.rb
closes #163 
closes #164 
- Currently only getting tasks for organisation. 
- Have replaced some `.where` with `.includes` to eager load resources and reduce number of queries. Correct me if I'm wrong @govuklaurence !
- There are no tests for the rake task yet, so perhaps I should add that to this PR, or do on a separate one. 
- Sure this could be refactored :)
> Link checker

- app/models/datafile.rb
- app/views/datafiles/edit.html.erb
- app/views/datafiles/edit_doc.html.erb
- app/views/datafiles/new.html.erb
- app/views/datafiles/new_doc.html.erb
- app/views/datasets/adddoc.html.erb
- app/views/datasets/addfile.html.erb
- app/views/datasets/frequencies/edit.html.erb
- app/views/datasets/frequencies/new.html.erb
- app/views/datasets/locations/edit.html.erb
- app/views/datasets/locations/new.html.erb
- spec/end-to-end-tests/tests/create.js
- spec/features/datasets_spec.rb
> Improve date validation and error messages

- app/models/datafile.rb
- app/views/datasets/edit.html.erb
Just a small one i forgot to commit earlier :P
fixes #196 and partially fixes an as yet unnamed issue
> Fix some validations, change wrong title

- app/models/dataset.rb
- spec/end-to-end-tests/tests/create.js
- spec/models/dataset_spec.rb
Validates that the title has at least 3 letters in it, and isn't just junk.
This fixes #205
> Make sure that the title is valid.

- app/views/datasets/frequencies/new.html.erb
'new' should post not put.
Fixes #202
> Fix redirect after empty frequency submission.

- app/views/datasets/licences/edit.html.erb
- app/views/datasets/locations/edit.html.erb
> When editing, Skip should be cancel

- Gemfile
- Gemfile.lock
> Use master as the branch previously used is now merged

- spec/end-to-end-tests/tests/create.js
> Correctly sets other_licence during tests

- app/views/datafiles/edit.html.erb
- app/views/datafiles/edit_doc.html.erb
- app/views/datafiles/new_doc.html.erb
> Make sure skip in documents goes to overview

- spec/end-to-end-tests/tests/edit.js
Fixes broken FE tests in master
> Fix admin check excluded

- app/controllers/datafiles_controller.rb
- app/views/datafiles/documents.html.erb
- app/views/datafiles/files.html.erb
- config/routes.rb
- spec/features/datasets_spec.rb
This closes #179 and #180 
Fixes the e2e tests around dataset and datalink deletion. But it's really horrible code - passing the file_id params around. Would be great to simplify #132 woop woop.
> Confirm delete datafiles

- db/seeds.rb
> Import default locations when seeding

- README.md
- lib/tasks/import.rake
- lib/tasks/sync.rake
- lib/util/metadata_tools.rb
Adds a rake task to import datasets which have been modified in the
last 24 hours (by asking live DGU for the metadata).
Fixes #236
> Imports changed datasets from live where change <24 hours ago.

- lib/tasks/import.rake
When loading organisations, will perform a second stage where the
organisation is assigned to the correct parent.
Fixes #252
> Assign organisations to hierarchy when loading

- app.json
This makes review apps' databases work
> Update app.json with postdeploy script

- app/models/datafile.rb
- app/models/dataset.rb
- app/models/link.rb
- config/locales/en.yml
Link to ticket:
https://waffle.io/datagovuk/publish_data_beta/cards/596f445968ba73003ebd576b
(Will do application text in another PR)
> [261] - Move model validation errors to locales

- Gemfile
- Gemfile.lock
- Procfile
- app/controllers/datasets_controller.rb
- app/models/dataset.rb
- app/workers/link_checker_worker.rb
- app/workers/publishing_worker.rb
- spec/spec_helper.rb
- spec/workers/link_checker_worker_spec.rb
- spec/workers/publishing_worker_spec.rb
* Sidekiq
* Publishing Worker
* Heroku config
> Background Jobs

- db/migrate/20170724104308_add_organisation_type.rb
- lib/tasks/import.rake
When importing organisations, we will now choose an organisation
type based on our desired filters.
Fixes #283
> Assign an org_type to each organisation on import

- lib/tasks/search.rake
Lower the batch size (again) and handle the error if the batch size is too large
> Bulk reindex fixes

- app/models/link.rb
- lib/tasks/import.rake
- lib/util/metadata_tools.rb
As a drive-by, also sets the INSPIRE guid which was missing in earlier import
> [DO NOT MERGE] Tries harder to import resources with dates attached

- app/models/link.rb
- lib/tasks/import.rake
- lib/util/metadata_tools.rb
This reverts commit 940c3acd09e73d2d6cfe4a3998631b780a4f51cc, reversing
changes made to 3cfaf16c1249417487b3cb6e5ed13de3693ef543.
> Revert "Merge pull request #297 from datagovuk/fix-import-dates"

- app/models/link.rb
- lib/util/metadata_tools.rb
Also sets the guid of the inspire metadata which was missing
Fixes #253
> Tries harder to fix import of dates

- Gemfile
- Gemfile.lock
- config/application.rb
I think we need to enable CORS on publish so that the organisation end point will respond to requests from find.
> Enable cors

- db/migrate/20170807111448_remove_unused_extensions.rb
> Add migration to remove extensions

- lib/tasks/search.rake
Do not analyze the dataset => name and dataset => organisation => name fields.
This will allow for exact match search queries
Relates to:
https://github.com/datagovuk/find_data_beta/pull/99
> Create mapping for elasticsearch

- db/schema.rb
- lib/tasks/search.rake
2 small changes:
- use ES_HOST environment variable
- show progress as you run rake:reindex
> Elasticsearch import

- app/controllers/datasets_controller.rb
- app/controllers/links_controller.rb
- spec/features/api/previews_spec.rb
Adds some more metadata to previews.
> Add new fields to preview api

- app/controllers/links_controller.rb
add dataset name to preview api
> add dataset name to preview

- setup.sh
Setup the app by running `./setup.sh`.
Setup includes:
* bundling Gemfile
* setting up the database
* downloading dumps
* seeding the database with locations, organizations and datasets
> Write app setup script

- setup.sh
- add # at the start
- use curl, as it's likelier to be installed
- reset the db in case it was already there
- clean up the big json files
> small changes:

- config/elasticsearch.yml
- config/initializers/elasticsearch.rb
- spec/spec_helper.rb
... from the VCAP_SERVICES environment variable
> If on PaaS, get the ES server URL and the server's cert

- config/elasticsearch.yml
- config/initializers/elasticsearch.rb
- spec/spec_helper.rb
@maxf - we need the value for the new VCAP_SERVICES env var
> Create elastic config for PAAS

- app/controllers/datasets_controller.rb
- spec/features/create_dataset_spec.rb
> DRY up DatasetsController

- app/controllers/docs_controller.rb
- app/views/docs/new.html.erb
> Refactor DocsController

- app/controllers/home_controller.rb
- app/controllers/manage_controller.rb
- app/models/dataset.rb
The end result of this refactor has more repetition, but it's for the best I think, as it makes the code easier to read and will make any further refactors that much easier.
I also noticed the sorting of the results by clicking on the column header does not work. I'll address that in another PR.
> Refactor ManageController

- .travis.yml
- manifest.yml
* Deploy the app automatically on a master merge to staging
* Travis handles the deploy
> Autodeploy staging

- db/migrate/20170807111448_remove_unused_extensions.rb
as that will also make PaaS crash
> Remove migration that refers to extension

- app/controllers/application_controller.rb
- app/controllers/docs_controller.rb
- app/controllers/links_controller.rb
- app/models/link.rb
- spec/factories/dataset.rb
- spec/factories/organisation.rb
- spec/features/create_dataset_spec.rb
- spec/features/edit_dataset_spec.rb
- spec/support/dataset_helper.rb
> Dry up specs with factories + fix skipped failing test

- app/controllers/application_controller.rb
- app/controllers/sync_controller.rb
- config/routes.rb
- lib/sync/legacy_datasets.rb
- lib/tasks/sync.rake
- spec/controllers/sync_controller_spec.rb
This is an updated PR. In response to feedback, api keys and associated model has been removed.  Chron job will need to add correct username and password as parameter urls as basic authentication is set for staging and production environments
> Create endpoint for syncing legacy datasets

- app/controllers/datasets/frequencies_controller.rb
- app/controllers/datasets/licences_controller.rb
- app/controllers/docs_controller.rb
- app/controllers/links_controller.rb
- app/views/datasets/show.html.erb
- app/views/docs/edit.html.erb
- app/views/docs/index.html.erb
- app/views/docs/new.html.erb
- app/views/links/edit.html.erb
- app/views/links/index.html.erb
- app/views/links/new.html.erb
- app/views/manage/_base.html.erb
- config/routes.rb
First step in a larger cleanup of the routes file.
> Treat links and docs as resources under datasets

- lib/tasks/datasets.rake
PaaS currently gives us only 512mb of RAM. The task loads all datasets into memory, which probably is causing the task to fail because of insufficient memory.
This updated task avoid loading all datasets into memory and relies exclusively on Postgres instead.
> Make task memory efficient

- app/controllers/concerns/update_legacy.rb
- app/controllers/datasets/frequencies_controller.rb
- app/controllers/datasets/licences_controller.rb
- app/controllers/datasets/locations_controller.rb
- app/controllers/datasets_controller.rb
- app/models/dataset.rb
- spec/controllers/datasets_controller_spec.rb
- spec/features/create_dataset_spec.rb
- spec/features/edit_dataset_spec.rb
- spec/models/dataset_spec.rb
this PR moves responsibility for updating legacy dgu with changes to metadata from the controller action to a call back on the dataset model
> refactor of the update legacy code 

- production-manifest.yml
- staging-manifest.yml
Fixes deploy issues (for now) with publish beta
> Use an older buildpack

- Gemfile
- Gemfile.lock
- lib/tasks/import.rake
- lib/tasks/sync.rake
- Fix import error (occurs when trying to parse JSON Lines file)
- Fetch legacy organisations via http rather than import from local file
- Add / consolidate logging
> FIX - import organisations rake task

- lib/tasks/import.rake
fix more bugs :)
relates to changes made on this pr https://github.com/datagovuk/publish_data_beta/pull/423
> correct class name

- production-worker-manifest.yml
- scripts/deploy-production.sh
- scripts/deploy-staging.sh
- scripts/deploy.sh
- staging-worker-manifest.yml
* You need to have a manifest.yml present or the deploy fails silently
* If `no-route: true` is set then the deploy fails fatally
> Workarounds for cf-bgd issues

- app/models/dataset.rb
- db/migrate/20171121123602_add_foi_contact_details_to_datasets.rb
- db/schema.rb
- lib/util/metadata_tools.rb
* create columns
* persist on import
* index new fields as JSON for ElasticSearch
Remember to reindex datasets in ES.
> Add contact and FOI details to dataset

- app/models/dataset.rb
- app/services/legacy/beta_to_legacy_sync_service.rb
- app/services/legacy/legacy_to_beta_sync_service.rb
- config/routes.rb
- lib/tasks/sync.rake
- spec/services/legacy/beta_sync_service_spec.rb
> Fix naming of sync classes

- app/services/legacy/dataset_import_service.rb
- lib/util/metadata_tools.rb
- spec/fixtures/legacy_dataset.json
- spec/services/legacy/dataset_import_service_spec.rb
This PR adds tests around our dataset import scripts.
> Test dataset import

- app/services/datasets_indexer_service.rb
- spec/services/datasets_indexer_service_spec.rb
Needed for https://github.com/alphagov/datagovuk_find/pull/331.
> Add datafile formats to index mapping

- app/models/dataset.rb
- app/models/link.rb
- app/services/legacy/dataset_import_service.rb
- scripts/deploy.sh
- spec/fixtures/daily_timeseries_dataset_with_invalid_date.json
- spec/fixtures/legacy_dataset.json
- spec/fixtures/monthly_timeseries_dataset_with_invalid_date.json
- spec/services/legacy/dataset_import_service_spec.rb
- Fixes for data importer (dates)
- Fix for deploy script
> Merge master into production

- .travis.yml
- scripts/deploy.sh
Fix for error in manifest creation resulting in deployments to cloud foundry via Travis to fail silently
> Fix Cloud Foundry Deployments

- .travis.yml
- Deploy to production if a tag is pushed to master
- Make the repo name a condition for deployment to cloud foundry
> Deployment Tagging

- app/services/legacy/dataset_import_service.rb
Mostly extracted local variable to a method, removed arguments where we could use the available `dataset` reader method and refactored for clarity.
> Refactor dataset importer

- config/database.yml
Some small tweaks to improve the database configuration file.
```command-line
$ bin/rails runner 'pp ActiveRecord::Base.configurations'                                                                                     {"default"=>
{"adapter"=>"postgresql", "encoding"=>"unicode", "pool"=>5, "url"=>nil},
"development"=>
{"adapter"=>"postgresql",
"encoding"=>"unicode",
"pool"=>5,
"url"=>nil,
"database"=>"publish_data_beta_development"},
"test"=>
{"adapter"=>"postgresql",
"encoding"=>"unicode",
"pool"=>5,
"url"=>nil,
"database"=>"publish_data_beta_test"},
"production"=>
{"adapter"=>"postgresql",
"encoding"=>"unicode",
"pool"=>5,
"url"=>nil,
"database"=>"publish_data_beta_production",
"username"=>"publish_data_beta",
"password"=>nil},
"staging"=>
{"adapter"=>"postgresql", …
```
> Streamline database config

- app/controllers/home_controller.rb
- app/models/dataset.rb
- app/views/home/dashboard.html.erb
> Count datasets with at least one datafile instead of counting datasets marked as published

- scripts/deploy-production.sh
- scripts/deploy-staging.sh
- scripts/deploy.sh
We have switched out the blue green deploy plugin with autopilot for our deploys on [Find](https://github.com/alphagov/datagovuk_find/pull/424). This PR implements the same change on publish.
> deploy with autopilot 

- app/models/dataset.rb
- app/models/theme.rb
- app/services/legacy/beta_sync_service.rb
- app/services/legacy/dataset_import_service.rb
- db/migrate/20180222152356_remove_theme_id_from_dataset.rb
- db/migrate/20180222153404_drop_themes_table.rb
- db/schema.rb
- db/seeds.rb
- lib/tasks/import.rake
- spec/services/legacy/beta_sync_service_spec.rb
- spec/services/legacy/dataset_import_service_spec.rb
We are using 'topics' instead in production
> Remove Themes

- app/models/dataset.rb
https://blog.codeship.com/rails-migrations-zero-downtime/
Thanks @laurentqro
> Tell ActiveRecord to ignore themes columns from its cache

- production-app-manifest.yml
- production-worker-manifest.yml
- staging-app-manifest.yml
- staging-worker-manifest.yml
This reverts commit 892ec0029c0b9ed9ebb21f3fd9c98f9b88667d3e.
> Revert "Upgrade Cloud Foundry buildpack (#526)"

- app/models/dataset.rb
- app/workers/dataset_import_worker.rb
- db/seeds.rb
- lib/tasks/sync.rake
Stuff remaining after 5482237f2c493ae9152a2353871a5531ca36c123
> Remove remaining themes-related code

- config/application.rb
- config/initializers/elasticsearch.rb
- Removes logging of potential secrets
- Leverages Rails' support for custom configuration to simplify things
> Refactor Elasticsearch initialiser

- Gemfile
- Gemfile.lock
- app/services/legacy/beta_sync_service.rb
- app/services/legacy/dataset_import_service.rb
- app/workers/beta_update_worker.rb
- config/initializers/sidekiq.rb
- config/redis.yml
- lib/tasks/import.rake
- lib/tasks/search.rake
- lib/tasks/sync.rake
- spec/services/legacy/beta_sync_service_spec.rb
- spec/spec_helper.rb
- Switches the application over to use common config for Sidekiq in GOV.UK applications – this gets us logs formatted correctly for our logging tools.
- Ensures logging information is correctly propagated when we sync data with legacy.
See https://trello.com/c/4rGs48M2
> Refactor logging

- scripts/deploy-production.sh
- scripts/deploy-staging.sh
- scripts/deploy.sh
- Configures autopilot to show application logs during application start so that we can debug if the application crashes
- Simplifies deployment scripts by removing unnecessary symlinking of manifest files
- Adds flag to deployment scripts so that they exit immediately if a step fails.
> Refactor deploy scripts

- Gemfile
- Gemfile.lock
Install the prometheus gem so that we generate metrics that it can
scrape.
> Install the prometheus gem

- README.md
- scripts/replication.sh
This is a first iteration at a script to simplify the process of setting up a working development environment.
The replication script will download a snapshot of the production data and restore it locally.
> Add replication script

- app/models/link.rb
- config/application.rb
- spec/validators/url_validator_spec.rb
This provides the same coding experience as when using files in app/
folders and fixes an issue where running a single test wouldn't work.
> Make rails autoload files in lib/validators

- spec/models/location_spec.rb
This is just testing the file is an ActiveRecord model - hopefully we can assume this ;-)
> Remove redundant location spec

- lib/tasks/import.rake
Imports the current details for a specific organisation from legacy, to
update things such as content details.
> Update organisation details from legacy

- app/controllers/tasks_controller.rb
- app/models/organisation.rb
- app/models/user.rb
- db/migrate/20180502142526_add_govuk_content_id_to_orgs.rb
- db/migrate/20180502150204_drop_organisation_users.rb
- db/migrate/20180502153341_map_gds_content_id_from_govuk.rb
- db/schema.rb
- db/seeds.rb
- spec/controllers/datasets_controller_spec.rb
- spec/factories/organisation.rb
- spec/factories/user.rb
- spec/models/organisation_spec.rb
https://trello.com/c/Jy6YRdzO/157-make-orgs-work
> Make orgs work

- app/views/datasets/datafiles/edit.html.erb
- app/views/datasets/datafiles/new.html.erb
- app/views/datasets/docs/edit.html.erb
- app/views/datasets/docs/new.html.erb
- app/views/datasets/edit.html.erb
- app/views/datasets/frequencies/edit.html.erb
- app/views/datasets/licences/edit.html.erb
- app/views/datasets/locations/edit.html.erb
https://trello.com/c/Rw90WNqS/169-add-missing-cancel-buttons-for-all-wizard-edit-pages
> Make sure all wizard pages have cancel buttons

- app/controllers/datasets_controller.rb
- app/views/datasets/show.html.erb
- config/locales/en.yml
- spec/features/edit_dataset_spec.rb
https://trello.com/c/XRQKhz80/158-add-additional-licence-fields
Fix for missing licences in view at end of creating new dataset.
(Replaces corrupted PR #610)
> Update view to show additional licence types

- app/views/datasets/frequencies/_frequency_options.html.erb
- app/views/datasets/frequencies/edit.html.erb
https://trello.com/c/Rw90WNqS/169-add-missing-cancel-buttons-for-all-wizard-edit-pages
This is consistent with the way we do licences.
> Move frequency options into a partial

- app/controllers/application_controller.rb
- config/application.rb
- config/initializers/raven.rb
https://trello.com/c/ZHZoiXNr/108-sentry-isnt-working
> Synchronise sentry config with find

- app/views/manage/_base.html.erb
- spec/features/manage_spec.rb
https://trello.com/c/Q7bfKmsu/186-remove-no-results-found-duplication
> Remove duplicate description for search results

- app/views/datasets/_errors.html.erb
- app/views/datasets/datafiles/edit.html.erb
- app/views/datasets/datafiles/new.html.erb
- app/views/datasets/docs/edit.html.erb
- app/views/datasets/docs/new.html.erb
- app/views/datasets/edit.html.erb
- app/views/datasets/frequencies/edit.html.erb
- app/views/datasets/frequencies/new.html.erb
- app/views/datasets/licences/edit.html.erb
- app/views/datasets/licences/new.html.erb
- app/views/datasets/locations/edit.html.erb
- app/views/datasets/locations/new.html.erb
- app/views/datasets/new.html.erb
- app/views/datasets/topics/edit.html.erb
- app/views/datasets/topics/new.html.erb
https://trello.com/c/VgPz1E2A/170-refactor-error-banner-into-a-shared-partial-file
> Refactor dataset error banners into partial

- app/views/datasets/datafiles/edit.html.erb
- app/views/datasets/datafiles/new.html.erb
- app/views/datasets/docs/edit.html.erb
- app/views/datasets/docs/new.html.erb
- app/views/datasets/edit.html.erb
- app/views/datasets/frequencies/edit.html.erb
- app/views/datasets/frequencies/new.html.erb
- app/views/datasets/licences/edit.html.erb
- app/views/datasets/licences/new.html.erb
- app/views/datasets/locations/edit.html.erb
- app/views/datasets/locations/new.html.erb
- app/views/datasets/new.html.erb
- app/views/datasets/topics/edit.html.erb
- app/views/datasets/topics/new.html.erb
https://trello.com/c/VgPz1E2A/170-refactor-error-banner-into-a-shared-partial-file
> Remove redundant div

- .travis.yml
Also fix the indents on some of the lists.
> Fix failing setup on travis

- app/controllers/datasets/frequencies_controller.rb
- app/controllers/datasets/licences_controller.rb
- app/controllers/datasets/locations_controller.rb
- app/controllers/manage_controller.rb
- app/controllers/tasks_controller.rb
This callbacks are already in place because these controllers inherit
from the application controller.
> Remove redundant authenticate_user! callbacks

- app/services/index_deletion_service.rb
- spec/spec_helper.rb
> Make sure we only clean up test indices

- app/services/ckan/v26/package_differ.rb
- app/workers/ckan/v26/sync_worker.rb
> Rename version diff class to PackageDiffer

- app/services/ckan/v26/link_mapper.rb
- spec/services/ckan/v26/link_mapper_spec.rb
> Make sure the link updated_at field is populated

- config/environments/staging.rb
https://trello.com/b/a30DSRUe/dgu-q1-doing
> Use the test CKAN API for sync on staging

- config/sidekiq.yml
https://trello.com/b/a30DSRUe/dgu-q1-doing
> Disable old sync on staging

- app/services/ckan/v26/dataset_mapper.rb
- spec/factories/ckan_v26_package.rb
- spec/services/ckan/v26/dataset_mapper_spec.rb
https://trello.com/b/a30DSRUe/dgu-q1-doing
> Fix missing custom licence information

- app/workers/ckan/v26/sync_worker.rb
- config/sidekiq.yml
> Schedule the new sync worker on staging (when it's working)

- lib/ckan/modules/json_reader.rb
- lib/ckan/modules/pagination.rb
- lib/ckan/v26/client.rb
> Turn off caching for the CKAN client

- lib/ckan/modules/url_builder.rb
> Looks like this form of cache busting doesn't work

- app/workers/ckan/v26/package_import_worker.rb
- app/workers/ckan/v26/package_sync_worker.rb
- config/sidekiq.yml
- spec/features/ckan_v26_package_import_spec.rb
- spec/features/ckan_v26_package_sync_spec.rb
https://trello.com/c/USyQ4NBd/389-sync-a-single-organisation-to-the-database-using-the-ckan-api
> Re-namespace workers to prepare for org sync

- app/models/organisation.rb
- app/services/ckan/v26/organisation_updater.rb
- app/workers/ckan/v26/ckan_org_import_worker.rb
- app/workers/ckan/v26/ckan_org_sync_worker.rb
- spec/features/ckan_v26_ckan_org_import_spec.rb
- spec/features/ckan_v26_ckan_org_sync_spec.rb
https://trello.com/c/6w4BSyGg/390-sync-a-single-organisation-to-find-using-the-ckan-api
> Propagate org updates to es

- spec/features/ckan_v26_ckan_org_sync_spec.rb
https://trello.com/c/6w4BSyGg/390-sync-a-single-organisation-to-find-using-the-ckan-api
> Add missing test for unpublishing draft datasets

- config/redis.yml
- production-app-manifest.yml
- production-worker-manifest.yml
- staging-app-manifest.yml
- staging-worker-manifest.yml
https://trello.com/c/rqZ4YcIh/172-use-redis-on-paas
> Switch to using PaaS redis instead of AWS

- config/sidekiq.yml
https://trello.com/c/6w4BSyGg/390-sync-a-single-organisation-to-find-using-the-ckan-api
This will only be merged when the task has been shown to work after running manually on staging and production.
> Schedule org sync to run daily

- README.md
https://trello.com/c/g07wP2X9/325-remove-old-sync-code-after-replacing-it-with-the-new-sync-code
This command no longer exists. Running sync will be documented in the
developer docs, as it spans more than one application.
> Remove call to bin/import in the README

- bin/setup
https://trello.com/c/3r6gUCTG/405-rewrite-the-dgu-developer-docs
> Run reindex when setting up from scratch

- db/migrate/20180502153341_map_gds_content_id_from_govuk.rb
- db/schema.rb
- db/seeds.rb
- production-app-manifest.yml
- staging-app-manifest.yml
https://trello.com/c/VvaTibq9/435-fix-publish-migrations-out-of-order
Previously some data changes were done in migrations, while others were
done in the seeds file. This creates issues where in some environments
either the migrations or the seeds are run, which caused some data to be
missing. Using the seeds as the single idempotent mechanism and running
them for all deployments will ensure longterm data integrity.
> Move data changes to idempotent seeds

- spec/lib/tasks/update_organogram_filenames_spec.rb
This file is only created for testing purposes and we should delete it 
afterwards.
> Delete file after test

- app/assets/stylesheets/components.scss
- app/assets/stylesheets/govuk-overrides.scss
Similar to https://github.com/alphagov/datagovuk_publish/pull/893
as the build is now failing on this.
Trello card: https://trello.com/c/LhIWTWKQ/1693-3-remove-dependency-which-is-blocking-deployment-of-dgu-publish
> Remove @includes in stylesheets

- app/controllers/datasets/datafiles_controller.rb
- app/controllers/datasets/docs_controller.rb
- app/controllers/datasets/licences_controller.rb
- app/controllers/datasets/locations_controller.rb
- app/controllers/datasets_controller.rb
- app/services/ckan/v26/dataset_updater.rb
- app/services/ckan/v26/inspire_updater.rb
- app/services/ckan/v26/link_updater.rb
- app/services/ckan/v26/organisation_updater.rb
- db/seeds.rb
- lib/tasks/update_organogram_filenames.rb
- spec/features/ckan_v26_ckan_org_import_spec.rb
- spec/features/ckan_v26_ckan_org_sync_spec.rb
- spec/features/ckan_v26_package_import_spec.rb
- spec/features/dataset_show_spec.rb
- spec/features/new_api/ckan_v26_package_import_spec.rb
- spec/models/datafile_spec.rb
- spec/models/dataset_spec.rb
- spec/services/ckan/v26/dataset_mapper_spec.rb
These were missed in https://github.com/alphagov/datagovuk_publish/pull/1002
> Fix linting issues

- scripts/deploy.sh
Fixed the deploy script by adding a space.
> Fix the deploy script for staging condition

- .github/workflows/ci.yml
- .travis.yml
Added github action test to allow for a faster test of PRs  as travis is no longer working.
https://trello.com/c/3MHhGs5C/2602-replace-travis-ci-with-github-actions-on-publish-and-find
> Add ci.yml for github actions

- app/lib/ckan/v26/depaginator.rb
- app/models/datafile.rb
- app/validators/url_validator.rb
- config/environments/development.rb
- config/environments/integration.rb
- config/environments/production.rb
- config/puma.rb
- lib/tasks/fix_existing_organogram_filenames.rake
- lib/tasks/update_organogram_filenames.rb
- scripts/set-credential.rb
- scripts/unset-credential.rb
- spec/features/ckan_v26_package_sync_spec.rb
- spec/lib/tasks/update_organogram_filenames_spec.rb
- spec/models/datafile_spec.rb
- spec/services/index_deletion_service_spec.rb
- spec/validators/url_validator_spec.rb
Fix the package test as it wasn't updated when the test data structure was updated.
Also fix linting issues due to updated rubocop
https://trello.com/c/DZJFi8z5/2613-create-prs-to-prep-for-29-upgrade
> Update package test as test data has changed

- .github/workflows/ci.yml
Fixed environment from staging to production for production deployments.
> Update ci.yml correct environment for production

- README.md
Elasticsearch has been replaced by Opensearch in PaaS
> Update README to use opensearch

- config/environments/integration.rb
- config/environments/staging.rb
https://trello.com/c/rYzT6RF3/1227-switchover-ckan-to-eks
> Update Integration and Staging CKAN base_url

- .github/workflows/build-image.yaml
- docker/Dockerfile
- docker/build-image.sh
Build the datagovuk_publish image files for use by the datatgovuk kubernetes cluster.
https://trello.com/c/nz3X804Y/1237-deploy-dgu-paas-apps-onto-integration-cluster
> Add build image files

- .github/workflows/build-image-on-tags.yaml
- .github/workflows/create-pr-on-tags.yaml
Update build image on tags to trigger on v prefix tags
https://trello.com/c/2qXYzZYb/1239-switchover-paas-apps-to-k8s-cluster
> Update build and create pr on tags with prefix v

- README.md
https://trello.com/c/2qXYzZYb/1239-switchover-paas-apps-to-k8s-cluster
> Update README.md deployment to kubernetes cluster

- README.md
- docker/Dockerfile
Adding the datagovuk user enables rails db processes
> Add a datagovuk user to the Dockerfile

- config/redis.yml
as REDIS_HOST was incorrectly setup
> Use REDIS_URL for redis config

- config/initializers/prometheus.rb
https://github.com/alphagov/govuk-dgu-charts/issues/122
> Initialise GovukPrometheusExporter.
