alphagov/datagovuk_publish

- Gemfile
- Gemfile.lock
Adds the govuk_frontend_toolkit gem to include the necessary scss and
templates.
> Add govuk_frontend_toolkit ruby gem

- config/application.rb
Stops dotenv trying to load in a production environment.
> Make CD possible for development

- app/controllers/application_controller.rb
Adds Basic Auth when in production and when HTTP_USERNAME and
HTTP_PASSWORD are set.  This can later be removed once we're happy
for people to start using it.
> Add Basic Authentication until ready for users.

- lib/tasks/import.rake
Given a jsonl encoded organisations list (from a live system dump) this
task will import (or update) organisations in the database.  Where the
name is in use, it will be overwritten by the values in the jsonl file.
```
rake import:organisations[path\to\dumpfile.jsonl]
```
The contents of the jsonl file are those retrieved from the daily dump of organisations and look like 
```json
{
"abbreviation": "ACC",
"approval_status": "pending",
"category": "local-council",
"contact-email": "",
"contact-name": "",
"contact-phone": "",
"description": "Aberdeen City Council",
"extras": [
{
"key": "abbreviation",
"value": "ACC"
},
{
"key": "category",
"value": "local-council"
},
{
"key": "contact-email",
"value": ""
},
{
"key": "contact-name",
"value": ""
},
{
"key": "contact-phone",
"value": ""
},
{ …
```
> Add rake command to import organisations

- app/controllers/tasks_controller.rb
- app/views/tasks/_base.html.erb
- app/views/tasks/my.html.erb
- app/views/tasks/organisation.html.erb
- db/seeds.rb
- spec/features/tasks_spec.rb
Changes the seeds to use a real organisation (which may be updated after
organisation import) and then uses those details rather than all datasets.
> Use a real org in the task page

- app/views/layouts/_proposition_header.html.erb
- app/views/layouts/application.html.erb
This makes sure the width of the logo section is narrow enough for the menu items to be on the same line.
Also cleaned up the proposition header.
> Make sure the header class is set

- app/controllers/manage_controller.rb
- app/views/manage/manage_organisation.html.erb
- app/views/manage/manage_own.html.erb
- app/views/manage/shared/_search.html.erb
- spec/features/manage_spec.rb
Allows users to filter down their datasets, or their organisation datasets by searching.
This will perform a case insensitive search across their (or organisation) datasets.
Changing tab with a search term specified should ensure the search-term is carried
across and applied when loading that page.  So a search for 'cats' in my datasets will
also be applied when I click on my organisations datasets.
> Add search to manage page

- README.md
- lib/tasks/overdue.rake
- lib/util/overduechecker.rb
Provides a rask task which can check (at an organisation or at a dataset level
) for datasets with a frequency that are overdue.
If the frequency is not set, or a task for the dataset already exists, then
it will ignore that dataset.  Otherwise it will find the end-date for the latest
datafile and check if the dataset is missing a more recent entry.
Will require changes/refactor once model associations are done, and we still need
to find a way to do this for the entire catalogue on a schedule (maybe only weekly
for overdue datasets).
part of #50
> Overdue tasks

- app/views/datasets/_dataset_field.html.erb
- app/views/datasets/adddoc.html.erb
- app/views/datasets/addfile.html.erb
- app/views/datasets/licence.html.erb
- app/views/datasets/new.html.erb
connected to #73 
- This PR adds missing class on text fields
- Nests the radio input within the radio label to fix styling.
Remaining issue: radio button styles only picked up if you land on the page after pressing skip on the previous page. If you've landed here from clicking submit (ie via Rails redirect_to) the styles aren't picked up. I think there is an issue with the js running on the page, maybe it's the order in which the assets are compiled? I don't know - I've not been able to fix it.
> Improves styling on dataset forms

- Gemfile
- Gemfile.lock
- app/controllers/datasets_controller.rb
- app/models/dataset.rb
- spec/models/dataset_spec.rb
Datasets need to be available via a friendly url so we are using the
friendly_id gem to generate the unique slugs for each dataset into the
name field.  This included removing the rails unique constraint on the
title.
Requires a ```bundle install```, no migration.
Closes #80
> Generates and uses slugs for datasets

- app/models/dataset.rb
- spec/models/dataset_spec.rb
When publishing the licence, frequency and at least 1 data file are
required, so this PR will enforce that validation when published=true.
Closes #82
> Enforce stricter validation when publishing.

- app/models/dataset.rb
- app/views/datasets/_dataset_field.html.erb
- app/views/datasets/new.html.erb
- spec/features/datasets_spec.rb
- spec/models/dataset_spec.rb
Makes sure that content matches that in alpha, and also puts the
field error in the correct place for the form element.
Closes #32
> Update validation content

- app/controllers/datasets_controller.rb
- app/views/datasets/_datafile_list.html.erb
- app/views/datasets/documents.html.erb
- app/views/datasets/files.html.erb
- config/routes.rb
- spec/features/datasets_spec.rb
Shows a list of user's files after some have been added to allow for adding
more than one during dataset creation.  Does the same for documentation.
Currently the edit links don't work, although adding a new one does.
Closes #105
> Adds files list and documentation list during dataset creation

- Gemfile
- Gemfile.lock
- app/models/ability.rb
- app/models/user.rb
- spec/models/user_spec.rb
Uses cancancan (bundle install required) to determine what publishers are
able to do.  The check can be done in each controller with
```
authorize! :update, @dataset
```
and will raise an exception if this is not allowed.
Once edit dataset is done, we can use this to check permissions for ```:create, :update, and :delete```
Closes #107
> Permission abilities

- app/assets/javascripts/application.js
- config/environments/staging.rb
- turbolinks not needed and cause errors with javascript in the body
- compile assets like in production - otherwise heroku tries to be clever but eventually fails to find some assets
> compile assets in staging

- app/controllers/manage_controller.rb
- app/helpers/manage_helper.rb
- app/views/manage/_base.html.erb
This is only used on the manage page, and so is only available at
pages in app/views/manage.
Fixes #142
> Creates a view helper for the FIND_URL

- app/helpers/datasets_helper.rb
I think this is a regression, where we tried to call .humanize on nil - so editing a draft
dataset where frequency hadn't been set made it explode
> Allows editing of drafts without frequency

- .travis.yml
- README.md
- app/controllers/datasets_controller.rb
- app/models/dataset.rb
- config/initializers/elasticsearch.rb
- lib/tasks/search.rake
- spec/features/datasets_spec.rb
When the user clicks publish (or republish) the dataset is now indexed in elastic. This includes the organisation, as well as datafiles (not separated) and any inspire metadata.
You can reindex all published datasets with ```rails search:reindex```
Config can be over-ridden by the presence of a elasticsearch.yml file in config/
Fixes #131 
Fixes #175
@govuklaurence @maxf @hannako You will need to have elasticsearch running on your machine after this PR.
> Indexes the dataset on publish

- app/views/datasets/show.html.erb
close #239 
Just display the dataset_title, rather than "Publish dataset_title" if the `current_path` is `confirm_delete`
> modify title based on current_page

- Gemfile
- Gemfile.lock
- app/models/organisation.rb
- db/migrate/2017071231151258_add_ancestry_to_organisations.rb
Uses the ancestry gem (https://github.com/stefankroes/ancestry) to add
support for organisations to use materialized path to mimic the
hierarchy.
> Allow organisations to exist in a hierarchy

- lib/tasks/import.rake
- lib/util/metadata_tools.rb
Also as a drive-by, renames get_doc_type to documentation? as suggested
by hannako elsewhere
> Better handle the 'other' licences on import

- app/controllers/datasets_controller.rb
- app/views/datasets/quality.html.erb
- config/routes.rb
- lib/quality/quality_score.rb
- lib/tasks/quality.rake
Temporarily adds a new page to allow us to see why we think a dataset
is bad quality, it is at /datasets/NAME/quality.  We may (or not) want
to integrate something similar at some point so that publishers know
why we consider a dataset bad quality.
New scores can be added to the class at /lib/quality/quality_score
by adding a new method that ends with _score, it should return an integer.
This is to close https://trello.com/c/Dbs1tDIg/226-quality-reporting-in-publish
> Adds a temporary page to view metadata quality.

- db/migrate/20170601084755_enable_uuid_extension.rb
- tools/paas.sh
Otherwise migrations break on Paas.
Also adds the paas.sh to workaround PaaS not leaving bin/rails in a runnable state when you ssh in to the container.  Should run as 
```
cd app
../tools/paas.sh bin/rails something....
```
> Remove attempt to load UUID extension

- Gemfile
- Gemfile.lock
- app/models/link.rb
- app/models/preview.rb
- db/migrate/20170731141237_add_previews.rb
- lib/preview/preview_generator.rb
- lib/tasks/preview.rake
This is the initial backend of the preview code.
Adds a new model linked to the link table, containing a json blob for
the preview of that link, if it's a CSV.
A new rake task ```preview:generate_all``` will iterate through the database
and find all links claiming to be CSVs (hint they're often not) and trying
to create a preview entry for them.
Because we don't have the faintest idea of what the encoding of the incoming CSV
is, we use the ```file``` command to find out what it is, and convert it to
UTF-8 if possible using iconv.
Still needs a UI, changes to dataset view to link to page and hooking in
to new links being created (as a sidekiq task). As preview blob is reasonably 
small, we might want to have it indexed with the link (or alternatively in a separate
index).
Requires a bundle …
> Adds a model and a rake task for generating previews.

- app/controllers/organisations_controller.rb
- config/routes.rb
- spec/features/api/organisations_spec.rb
Can list all organisations at /api/organisations or query by passing a
query param called q like /api/organisations?q=cabin
> Create an organisations API endpoint

- app/controllers/links_controller.rb
- app/models/link.rb
- app/models/preview.rb
- config/routes.rb
- db/migrate/20170731141237_add_previews.rb
- lib/preview/preview_generator.rb
- spec/features/api/previews_spec.rb
When a file id is given to /api/previews/:file_id then it will return a JSON
blob containing enough information to show a preview of the file.
e.g
```json
{
id: 1,
link_id: 11,
content: {
type: "CSV",
body: [
[
"Name:",
"Age"
],
[
"Bob",
"23"
],
[
"Fred",
"24"
],
[
"Jane",
"22"
]
]
},
created_at: "2017-08-02T14:23:03.710Z",
updated_at: "2017-08-02T14:23:03.710Z"
}
```
> A preview API

- app/models/dataset.rb
- app/models/theme.rb
- db/migrate/20170804132533_add_theme_table.rb
- db/migrate/20170804132655_add_theme_field_to_dataset.rb
- db/seeds.rb
- lib/tasks/import.rake
- lib/tasks/sync.rake
- lib/util/metadata_tools.rb
When importing legacy datasets, this PR will attach a reference to an entry in the Theme
table so that we don't lose data.  We won't be displaying this anywhere right now though.
Some datasets don't have themes, in which case this will be nil.
The default themes are created in db:seed so this will need to be run for themes to be
created before import, otherwise there will be no theme references.
> Import Themes

- lib/util/metadata_tools.rb
We store the frequency as `frequency` not `update_frequency` which is why all the datasets have a frequency of never atm.
> fix bug on import

- app/helpers/manage_helper.rb
- app/models/dataset.rb
- db/migrate/20170823141113_add_last_updated_at_to_dataset.rb
- db/schema.rb
- lib/util/metadata_tools.rb
- spec/rails_helper.rb
- spec/support/dataset_helper.rb
- This is the back end part of the fix for this [pr](https://github.com/datagovuk/find_data_beta/pull/180). 
- We are storing the value in `metadata_modified` on the legacy dataset in `dataset.last_updated_at`
- This PR also gets the `geographic_coverage` value from legacy datasets and stores in in `location1`
> Get location and last updated from legacy datasets

- Procfile
- docs/first-time-setup.md
It was reduced to 1 initially because sidekiq was eating all the redis connections. We have 20 and I'm not letting sidekiq have 10 connections.
This should in theory increase the job processing rate tenfold.
> Allow more workers on sidekiq

- lib/tasks/import.rake
Process line by line instead of loading the whole file in memory.
We have no control over the size of the files we're processing, so it's probably a good idea to be defensive here.
> Avoid file slurping

- lib/validators/url_validator.rb
- spec/features/edit_dataset_spec.rb
- spec/spec_helper.rb
- spec/validators/url_validator_spec.rb
There is a bug on publish where valid url's were failing the `validDomain?` check raising a 'Url does not contain a valid domain' in the console. eg this valid link was failing:
https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/49810/582.xls
I think it was an issue with how we were querying the Whois server.
Removing the validation on domain fixes this bug, and doesn't feel like a bad thing to do as we check url is a valid path via RestClient. Plus the user only sees one error message "Please enter a valid URL" regardless of the underlying error so we aren't depriving them of useful debugging information by removing the check on domain.
> fix bug on datafile url validation

- app/models/dataset.rb
- config/elasticsearch.yml
- config/initializers/elasticsearch.rb
- lib/tasks/search.rake
I think it's more flexible to allow the app to read from VCAP_SERVICES even locally. That way it's possible to access a PaaS elasticsearch server by setting VCAP_SERVICES in your terminal.
Other changes are around better error handling. See respective commits.
> Vcap config fix

- lib/util/metadata_tools.rb
Reverts datagovuk/publish_data_beta#322
- This was right as it was. 
- The [`convert_frequency`](https://github.com/datagovuk/publish_data_beta/blob/393c4664a3c88672d0d4f8f7ac2d830dfba91502/lib/util/metadata_tools.rb#L10) function is taking the value stored in the legacy dataset key `update_frequency`, converting that value to match those we are handling in find beta, and then saving that value on `dataset.frequency`
- The [bug we currently have on production ](https://find-data-beta.herokuapp.com/dataset/cats-per-square-kilometre)is hopefully just because the [reindex failed](https://github.com/datagovuk/publish_data_beta/blob/393c4664a3c88672d0d4f8f7ac2d830dfba91502/lib/tasks/search.rake#L29). @maxf  is checking tomorrow :)
> Revert "fix bug on import"

- app/models/dataset.rb
- app/views/datasets/edit.html.erb
- app/views/manage/_base.html.erb
- spec/controllers/datasets_controller_spec.rb
- spec/features/harvested_dataset_spec.rb
- spec/support/devise.rb
Each time a dataset is harvested, it is updated in Publish. If a publisher edits a harvested dataset, the changes will be overwritten at the next harvest. To prevent that, we want to make such datasets readonly.
This PR
* checks if dataset is harvested
* hides Add Data and Edit links if dataset is harvested
* aborts update of a harvested dataset and displays error message to the user
Note that the import and sync rake tasks skip validation when updating a dataset, so we're all good on that front.
https://trello.com/c/Fclrjhei/5-harvested-datasets-are-read-only-on-publish-beta
This PR prevents harvested datasets from being edited by the user from the UI - i.e. the 'edit' button is hidden in the view and the guard clause is present only in the `update` controller action.
However, a …
> Harvested datasets are readonly

- config/initializers/sidekiq.rb
- config/redis.yml
Now that we've included the Sidekiq servers in the manifest (https://github.com/datagovuk/publish_data_beta/pull/360), we can configure and initialize Sidekiq for staging and production.
> Configure and initialize Sidekiq

- config/initializers/sidekiq.rb
We are using symbolized instead of quoted keys to grab the configuration values from the yaml file, so values were not showing up. Using stringed keys fixes the issue. Also added network timeout option.
Follows https://github.com/datagovuk/publish_data_beta/pull/361.
> Fix Sidekiq config + add timeout option

- app/helpers/application_helper.rb
- app/views/manage/manage_own.html.erb
We need to specify the protocol in the `#find_url` helper in order to avoid having Rails insert the protocol + domain of the server the app is currently running on.
This PR fixes the external links to Find: the dataset title in the list of managed datasets, and the _View it_ link that shows in the flash message after a dataset has been published.
> Fix Find URL on dataset link

- app/controllers/sync_controller.rb
- config/routes.rb
- spec/controllers/sync_controller_spec.rb
- Revert POST to GET request to sidestep CSRF error. Not ideal but
hoping this is ok given this is a temporary endpoint with limited
security risks
> FIX - Legacy Sync

- .cfignore
The end-to-end tests are over 50MB! The entire app is about 200KB. Let's not upload the specs.
> Don't deploy specs

- app/controllers/datasets_controller.rb
- app/models/dataset.rb
- spec/controllers/datasets_controller_spec.rb
- spec/models/dataset_spec.rb
Building a dataset's slug with its uuid and parameterized title is both nice to read and unique. This will ensure we avoid any clashes with existing slugs in Legacy.
example slug: `http://foo.com/datasets/ca0902fb-08bb-46f4-8a96-ee8866b9e673-my-dataset`
Trello card: https://trello.com/c/85fqAa19/32-prevent-slug-duplicates-across-legacy-and-beta
> Build slugs with dataset uuid and title

- app/models/legacy/dataset.rb
The day we add another status (like "discarded", for example), this will erroneously return `true`. The only way to tell whether a dataset is unpublished is if its status is anything else than `"published"`.
`!dataset.published?` ensures we identify a dataset as _not published_ regardless of how many new statuses we may add in the future.
> An unpublished dataset is not necessarily a draft

- app/models/dataset.rb
- spec/features/create_dataset_spec.rb
- spec/models/dataset_spec.rb
We were setting the slug before the uuid had been generated, so the slug was showing with no uuid in the slug for new records, even though it did work when updating an existing record.
This PR ensures we set the dataset's `uuid` as soon as it is initialised, which fixes the bug.
> Fix slug bug on create

- app/controllers/datasets_controller.rb
- app/models/dataset.rb
- db/migrate/20171006145144_remove_published_from_datasets.rb
- db/schema.rb
**BEFORE** merging this PR, please make sure you:
Follows up on https://github.com/datagovuk/publish_data_beta/pull/349.
The migration of the data from the `published` column to the `status` column has run successfully, so we can now safely remove the `:published` boolean column from the `datasets` table.
> Remove :published boolean column from datasets table

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/datasets_controller.rb
- app/models/ability.rb
- app/models/legacy/server.rb
- app/models/user.rb
- spec/controllers/datasets_controller_spec.rb
- spec/models/user_spec.rb
Currently, any dataset can be read and edited by any user. This PR makes sure only users with the following characteristics can view or edit a given dataset:
* user belongs to the organisation that owns the dataset
* user's primary organisation owns the dataset
Trello card: https://trello.com/c/7bSWFsV4/43-on-publish-beta-a-user-can-only-a-edit-dataset-that-they-have-permission-to-edit
Uses the CanCanCan gem: https://github.com/CanCanCommunity/cancancan
> User read/update permissions for datasets

- app/models/legacy/dataset.rb
- db/migrate/20171024135704_add_legacy_name_to_dataset.rb
- db/schema.rb
- lib/util/metadata_tools.rb
- spec/factories/dataset.rb
- spec/models/legacy/dataset_spec.rb
This makes sure we can:
* redirect any links to legacy to its new URL in the new Publish app
* avoid overwriting the names (slugs) in legacy, which breaks links
> Store legacy dataset name on publish beta dataset

- app/controllers/datasets/docs_controller.rb
- app/controllers/datasets/frequencies_controller.rb
- app/controllers/datasets/licences_controller.rb
- app/controllers/datasets/links_controller.rb
- app/controllers/datasets/locations_controller.rb
- app/controllers/datasets_controller.rb
- app/models/dataset.rb
- app/views/datasets/docs/edit.html.erb
- app/views/datasets/docs/index.html.erb
- app/views/datasets/docs/new.html.erb
- app/views/datasets/edit.html.erb
- app/views/datasets/frequencies/edit.html.erb
- app/views/datasets/frequencies/new.html.erb
- app/views/datasets/licences/edit.html.erb
- app/views/datasets/licences/new.html.erb
- app/views/datasets/links/edit.html.erb
- app/views/datasets/links/index.html.erb
- app/views/datasets/links/new.html.erb
- app/views/datasets/locations/edit.html.erb
- app/views/datasets/locations/new.html.erb
- app/views/datasets/new.html.erb
- app/views/datasets/show.html.erb
- app/views/manage/_base.html.erb
- config/routes.rb
- spec/controllers/datasets_controller_spec.rb
- spec/features/create_dataset_spec.rb
- spec/features/edit_dataset_spec.rb
- spec/models/dataset_spec.rb
This PR introduces:
* new URLs for datasets. The URL structure is now: `/datasets/:uuid/:name`, where name acts as the datasets URL slug,
* generates a new slug every time a dataset's title changes,
* redirects of any dataset URL with an old slug to the URL with the latest up to date slug. The slug is now entirely cosmetic. As long as the `:uuid` is correct in `/datasets/:uuid/:name`, the user will be directed to the correct dataset.
trello: https://trello.com/c/bTQ1Nspf/48-in-publish-beta-redirect-dataset-urls-with-old-slugs-to-the-latest-version-the-url-in-order-to-avoid-broken-links-when-a-dataset
> Homemade slugs with custom routes

- app/models/dataset.rb
Otherwise, setting the frequency or the licence will trigger a push,
even before the dataset is published
> Only push to legacy when publishing a dataset

- app/controllers/datasets/links_controller.rb
- app/models/dataset.rb
- app/models/legacy/dataset.rb
- app/models/link.rb
- app/views/datasets/frequencies/edit.html.erb
- app/views/datasets/frequencies/new.html.erb
- app/views/datasets/links/_date_field.html.erb
- app/views/datasets/links/_month_input.html.erb
- app/views/datasets/links/_quarter_inputs.html.erb
- app/views/datasets/links/_year_input.html.erb
- app/views/datasets/links/edit.html.erb
- app/views/datasets/links/new.html.erb
- spec/features/create_dataset_spec.rb
- spec/models/dataset_spec.rb
- spec/rails_helper.rb
There is no clear user need (legacy only has 10 datasets marked as weekly). It makes full sync with legacy possible, resulting in an easier transition for publishers.
This PR removes the `weekly` option for datasets and introduces the requirement for dates when creating datafiles for daily datasets.
Trello: https://trello.com/c/DTTDnTUv/53-remove-weekly-frequency-from-datasets
> Remove dataset weekly frequency + add dates to daily datafiles

- app/workers/legacy_publish_to_elastic_worker.rb
- lib/tasks/import.rake
- lib/tasks/sync.rake
- lib/util/legacy_dataset_sync.rb
- lib/util/metadata_tools.rb
- spec/controllers/datasets_controller_spec.rb
- spec/lib/util/legacy_dataset_sync_spec.rb
- When syncing legacy make sure org data is indexed too!
- Refactor sync task
- Add test coverage for when there are no datasets to import
- Add more logging to aid debugging on staging and prod
> Make sure that organisation data is indexed when syncing datasets

- app/controllers/datasets_controller.rb
- app/models/dataset.rb
- app/views/datasets/links/index.html.erb
- spec/features/create_dataset_spec.rb
Dataset `stage` logic introduced with https://github.com/datagovuk/publish_data_beta/commit/f7b182f4 seems to be unused.
We set the dataset's stage to `completed` when the user reaches the last step of the dataset creation process, and when a dataset is published. But the only place we check the stage of a dataset is in a view where we check whether the value is `"initialised"`.
> Remove seemingly obsolete 'stage' logic

- app/models/dataset.rb
- db/migrate/20171108155801_remove_stage_from_datasets.rb
- db/schema.rb
Removes obsolete column `stage` from the `datasets` table.
Follows https://github.com/datagovuk/publish_data_beta/pull/413.
> Remove stage column from datasets table

- app/helpers/application_helper.rb
- app/views/manage/_base.html.erb
- app/views/manage/manage_own.html.erb
- lib/tasks/search.rake
This PR updates Elastic Search's mapping to include `uuid`, so Find can get a dataset by its uuid.
Sister PR for Find: https://github.com/datagovuk/find_data_beta/pull/310.
> Update structure of FIND dataset URLs

- app/views/manage/manage_own.html.erb
The hash we are accessing to get the dataset uuid and name is not with indifferent access, so using symbolized keys returns `nil`. Which means the `find_url` method cannot put together the link to FIND. This PR changes to stringed keys.
> Fix view it link

- staging-app-manifest.yml
We're currently hitting our memory limit on PaaS because we're launching more apps now. I've reduced the amount of memory the staging app server uses by half.
> Reduce memory for publish staging

- production-worker-manifest.yml
- staging-worker-manifest.yml
Blue green deploys wipe out some of the settings, and this is one i'd forgotten about. Since sidekiq doesn't expose itself on `:80`, it's better to just check that the process is active instead. This was the behaviour before but it is not being repro'd in new deploys.
> Use process health check on workers

- app/services/alias_updater_service.rb
- app/services/datasets_indexer_service.rb
- app/services/index_deletion_service.rb
- lib/tasks/search.rake
- spec/services/index_deletion_service_spec.rb
- Includes fast-fail if an index exists with the same name as the alias. This index needs to be deleted manually before continuing. 
- Fixes for error handling and default batch size. 
- Improved error messaging.
> Fixes for search.rake

- lib/tasks/cloud_foundry.rake
- production-app-manifest.yml
- staging-app-manifest.yml
This reverts commit c6b3d904dd731c80960d89ab6866cff56b3e291a, which was causing deploys to fail.
> Revert "Automate db migration on cloud foundry (#445)"

- lib/tasks/import.rake
In staging environment datasets should be imported from 'test.data.gov.uk' - this is the value of LEGACY_HOST in staging (in production LEGACY_HOST is 'data.gov.uk')
> Reinstate LEGACY_HOST env var

- app/models/dataset.rb
ActiveRecord caches table columns, and uses this cache to build INSERT statements. Even if the code is not touching that column, ActiveRecord will still attempt to set it to NULL when saving models.
https://blog.codeship.com/rails-migrations-zero-downtime/
> Remove column removal patches

- scripts/unset-credential.rb
When we update a User-provided Service Instance, new credentials overwrite old credentials, and parameters not provided are deleted (source: https://docs.cloudfoundry.org/devguide/services/user-provided.html).
This script allows us to delete a credential without deleting - well - everything, very much like https://github.com/datagovuk/publish_data_beta/blob/master/scripts/set-credential.rb does for adding/updating a credential.
> Script to delete an environment variable on PaaS

- app/models/additional_info.rb
- app/models/dataset.rb
- app/services/legacy/dataset_import_service.rb
- spec/fixtures/legacy_dataset.json
- spec/services/legacy/dataset_import_service_spec.rb
In order to make it easier to display legacy 'additional info(s)' on find beta these datafile types are moved to their own model (AdditionalInfo) rather than sharing the Doc model with non-timeseries datafiles. As with Link and Doc, AdditionalInfo inherits from Datafile and utilises single table inheritance.
Please note that this is a first step in order to fix displaying of additional info on find. I suggest also that the models are reviewed in a future PR as its hard to ascertain what they represent in reality.
There is a corresponding PR on find to display additional info
https://github.com/alphagov/datagovuk_find/pull/324
After merging we will need to reimport / reindex staging and prod
> Add AdditionalInfo Model

- app/models/additional_info.rb
- app/models/dataset.rb
- app/services/legacy/dataset_import_service.rb
- spec/fixtures/legacy_dataset.json
- spec/services/legacy/dataset_import_service_spec.rb
This reverts commit a54347eaf2b7f9bc6efc7ef6b892a04e1f82e27d.
There appears to be an issue when trying to import legacy datasets on Publish Staging (out of memory). These changes can be reinstated once fixed. A PR to revert corresponding changes on Find can be found here - https://github.com/alphagov/datagovuk_find/pull/325
> Revert "Add AdditionalInfo Model (#462)"

- README.md
- lib/tasks/import.rake
This PR reverts recent changes made to the import.rake task in order to prevent an out of memory issue on cloud foundry
> Do not let Rails download and unzip legacy datasets - revert to previous manual process

- app/models/dataset.rb
- app/services/datasets_indexer_service.rb
This PR makes sure we include the dataset `legacy_name` in the ES index, so we can use it in Find to redirect from legacy URLs to the new ones.
Trello: https://trello.com/c/HbtA8f6l/165-make-legacy-dataset-urls-work-in-find-l
PR in FIND: https://github.com/alphagov/datagovuk_find/pull/327.
> Map dataset :legacy_name in ElasticSearch index

- app/services/datasets_indexer_service.rb
- spec/spec_helper.rb
So we don't have to maintain two mappings, both in the code
and the test helper. This was causing tests to inadvertently
run against an outdated index.
> Keep index mappings in one place

- config/application.rb
Any rake task ran on staging environment with `RAILS_ENV=test` fails because the `dotenv` gem is only installed on test and development environments.
And actually, we don't even need that for `dotenv` to work.
https://github.com/bkeepers/dotenv
> Remove unnecessary require

- app/services/datasets_indexer_service.rb
- spec/services/datasets_indexer_service_spec.rb
Accidentally removed the `legacy_name` from the mappings when I did this refactor here https://github.com/alphagov/datagovuk_publish/pull/467/files.
I added a test so it doesn't happen again :)
> Add legacy_name to ES index mapping

- app/models/dataset.rb
- spec/models/dataset_spec.rb
Set last_updated_at on `Dataset#publish!`. Its absence is currently causing FIND to error when a user visits a dataset.
> Set last_updated_at on `Dataset#publish!`

- app/models/datafile.rb
- app/models/dataset.rb
- app/models/link.rb
- app/services/legacy/dataset_import_service.rb
- spec/fixtures/legacy_dataset.json
- spec/services/legacy/dataset_import_service_spec.rb
This PR:
- add the option of `irregular frequency` for imported datasets
- imports from `package['resources']`, rather than importing from `timeseries_resources`, `additional_resources` etc.
> import from resources only

- app/models/link.rb
- app/services/legacy/dataset_import_service.rb
- spec/services/legacy/dataset_import_service_spec.rb
This PR makes the way we set `start_date` and `end_date` on datafiles consistent across legacy and publish.
Previously start date and end date were being set by the `dataset_import_service`. 
However there was also a `before_save` on the link model to set `end_date`. 
This meant:
- Imported datafiles were having end date set twice.
- Imported datafiles had both start and end dates
- Published datasets would always have a start_date of nil.
Removal of either one of start or end date on the Link model adds complexity to Find.
> Set dates consistently across legacy and publish datafiles

- app/models/dataset.rb
- spec/features/datafile_spec.rb
- spec/features/edit_dataset_spec.rb
- spec/models/dataset_spec.rb
- spec/support/dataset_helper.rb
A publisher should be able to publish a dataset with no datafile.
https://trello.com/c/Jb4ablla/70-as-a-user-of-publish-i-can-publish-a-dataset-that-has-no-datafiles
> User can publish dataset with no datafile

- .travis.yml
https://trello.com/c/GiixWO8N/31-implement-github-tagging-for-production-deployments
> Change git release tagging convention to vX.X.X

- app/services/legacy/dataset_import_service.rb
- spec/services/legacy/dataset_import_service_spec.rb
This PR relates to: https://trello.com/c/fRUSfgum/124-datafiles-imported-from-legacy-have-their-parent-datasets-creation-date-rather-than-their-own-creation-date-xs
It will also help implement this: https://trello.com/c/matLU6mH/48-make-last-updated-consistent-on-dataset-show-page
- We are currently setting a datafile's creation date to that of its parent dataset.This seems unnecessary because resources have their own `created` date, we should store this instead.
```
"resources": [
{
"hash": "",
"description": "download",
"created": "2015-12-17T12:09:03.088202",
"url": "http://www.emodnet-seabedhabitats.eu/download",
"format": "HTML",
"qa": { },
"tracking_summary": {},
"resource_locator_function": "download",
"archiver": {},
"resource_locator_protocol": "",
"position": 0,
"revision_id": …
```
> Set datafile creation date on import

- lib/tasks/import.rake
This PR relates to https://trello.com/c/VVoQtElX/123-imported-datasets-have-no-end-date
There is some old code which is skipping the setting of `end_date` on `datafile.save`. 
```
pry(main)> Link.count
=> 80710
pry(main)> Link.where.not(start_date: nil).count
=> 22359
pry(main)> Link.where.not(end_date: nil).count
=> 0
```
This PR removes that code.
> Set end date on import of datafile

- app/services/datasets_indexer_service.rb
- spec/services/datasets_indexer_service_spec.rb
Implements a lowercase normalizer for Elastic Search.
This is to make sure Elastic Search tokenizes file formats regardless of case, i.e. "csv" and "CSV" are both tokenized to "csv".
For https://github.com/alphagov/datagovuk_find/pull/360.
https://trello.com/c/r5koAzWE/128-find-bug-datafile-format-filter-list-shows-both-upcased-and-downcased-file-formats
> Use lowercase normalizer to tokenize datafile formats

- app/services/datasets_indexer_service.rb
- spec/services/datasets_indexer_service_spec.rb
Following renaming of models on publish (ref: https://github.com/alphagov/datagovuk_publish/pull/493) we should have updated the ES mappings. This PR makes that update.
> Add new ES mapping for docs

- app/services/legacy/organisation_import_service.rb
- lib/tasks/active.rake
- lib/tasks/import.rake
- spec/fixtures/legacy_organisation.json
- spec/services/legacy/organisation_import_service_spec.rb
In Find, we display contact details present on the dataset. If they are not present, we fetch the contact details from its parent organisation. Many datasets had no contact details because their parent org had none.
Actually, no organisation in Beta had any contact details, because the import was using wrong keys to retrieve them.
This PR fixes the import and adds test coverage.
https://trello.com/c/iGmqyQAm/126-make-sure-dataset-contact-details-are-present-on-the-organisation-model
> Test and fix legacy organisations import

- app/services/legacy/dataset_import_service.rb
- spec/services/legacy/dataset_import_service_spec.rb
This PR relates to https://github.com/alphagov/datagovuk_publish/pull/495
When we import a dataset, the Link's `created_at` date is set to the resource's `created_date`. However, sometimes this field is nil, for reasons only ckan knows. This PR set's the link's `created_at` date to the parent package's `created date`, if that's the case.
> Set Link created date 

- app/services/legacy/organisation_import_service.rb
`#update_columns` was failing silently because we were setting an invalid value for `ancestry`. Reverting to a more straighforward and simple way. It will be slower, but for 1400 something records, it's no big loss. Better to concentrate our efforts to speed up imports of datasets.
> Fix organisation importer

- app/workers/dataset_import_worker.rb
- config/sidekiq.yml
- lib/tasks/import.rake
Dataset imports are painfully slow, so this is an attempt at speeding up the process.
It also has these added benefits:
* we can run multiple imports in parallel (= `RAILS_MAX_THREADS` or `5` by default)
* easy to track progress and errors on a dataset-per-dataset basis
* doesn't take memory away from the Rails application
* in their own queue, so we don't interfere with regular mission-critical jobs, that currently go into the `default` queue
> Handle dataset import with background job

- app/services/index_deletion_service.rb
- spec/services/index_deletion_service_spec.rb
Following a re-index, the newly created index would be deleted if the total number of indexes was less than three. Tests were giving false positives :-(
> Bug-fix: Elasticsearch re-index cleanup

- app/models/dataset.rb
- app/models/link.rb
- app/services/datasets_indexer_service.rb
- db/migrate/20180126120418_add_short_id_to_dataset.rb
- db/migrate/20180128210121_add_short_id_to_link.rb
- db/schema.rb
- spec/models/dataset_spec.rb
- spec/models/link_spec.rb
- spec/services/datasets_indexer_service_spec.rb
Corresponding PR for Find Beta - https://github.com/alphagov/datagovuk_find/pull/374
https://trello.com/c/kt5eSCvX/46-shorten-dataset-urls
The data model now stores a short id (6 characters long) which will replace the use of uuid's in urls. Short ids are unique (there are checks to confirm no two short ids are the same)
*New url format*
http://localhost:3000/dataset/oGckXH/[dataset-name]/datafile/pXcFXt/[datafile-name]
> Generate short ids for Datasets and Links

- app/models/dataset.rb
- app/models/link.rb
The first parameter in the urlsafe_base64 method specifies the length
in bytes, not the length in characters. Param changed from 8 to 6 to
generate a short_id with character length of 8.
> Correction to short_id generation

- Procfile
Concurrency is configured in `config/sidekiq.yml`. The default mirrors that of the database connection pool so that enough database connections are available for the number of worker processes.
If we want to override the concurrency value we should run foreman with a RAILS_MAX_THREADS environmental variable set.
> Fix sidekiq concurrency

- app/workers/link_checker_worker.rb
- config/sidekiq.yml
Delegate link checking to a background job to speed up the process and make debugging easier.
> Delegate link checking to a background job

- app/services/link_checker_service.rb
- lib/tasks/check.rake
- spec/services/link_checker_service_spec.rb
* skip link validation on save
* defer to `Ruby Net::HTTP` for checking if response is a success
* save the response error message onto the `Task` description for better reporting
* enforce a timeout for requests
* add a rake task to check all links in the DB
> Smarter link checker

- app/services/legacy/dataset_import_service.rb
- spec/fixtures/legacy_dataset.json
- spec/services/legacy/dataset_import_service_spec.rb
In the dataset importer, we select datafiles based on their `resource_type`. If it's `file`, they're a datafile, if it's `documentation`, they're supporting documentation.
However, it turns out not all datafiles are created equal in legacy. Some don't have a `resource_type` field. As a result, they get ignored.
This makes sure we import all datafiles. We recognize datafiles to be files if they are not documentation. This is not ideal, because it could be that some supporting documents have no `resource_type` either, but at least no one gets left behind, and we can iterate once we know more about this.
https://trello.com/c/xK99B0fA/95-missing-datafiles-on-find
> Datafiles with no resource_type are datafiles too

- app/services/legacy/dataset_import_service.rb
- db/seeds.rb
- lib/tasks/import.rake
- lib/tasks/sync.rake
- spec/fixtures/legacy_dataset.json
- spec/services/legacy/beta_sync_service_spec.rb
- spec/services/legacy/dataset_import_service_spec.rb
Oh legacy! You and your ways.
Certain topics were not being imported because we were not matching against '&'.
Added some tests for building the topic_id (and theme_id)
Please not that Themes are deprecated in favour of Topics. Once this gets a thumbs up on prod there will be another PR raised to clean up Themes
**Trello card**
https://trello.com/c/Ot65Qefh/80-implement-topics-themes-l
> FIX - import missing topics from legacy

- app/services/datasets_indexer_service.rb
- lib/tasks/import.rake
Run import and reindex tasks synchronously until we can fix Redis memory issues.
> Run import and reindex tasks synchronously

- app/services/datasets_indexer_service.rb
Fix undefined local variable error introduced in https://github.com/alphagov/datagovuk_publish/pull/522.
> Fix undefined local variable error in datasets indexer

- app/services/datasets_indexer_service.rb
- spec/services/datasets_indexer_service_spec.rb
String types are no longer supported in Elasticsearch 6.0. The string field has split into two new types: text, which should be used for full-text search, and keyword, which should be used for keyword search.
The previous mappings are currently working because Elasticsearch 5.0 has backward compatibility that is removed with Elasticsearch 6.0.
See https://www.elastic.co/blog/strings-are-dead-long-live-strings
> Upgrade deprecated Elasticsearch string types

- config/initializers/elasticsearch.rb
PAAS has changed the elasticsearch config in VCAP_SERVICES
```
As someone testing our private beta Elasticsearch service we're letting you know that we're changing the way you connect to it from your PaaS applications. We will keep things backwards compatible until no sooner than 19th February 2018.
Elasticsearch allows clients to connect to multiple Elasticsearch hosts. This helps with availability and the balancing of load. Up until now we have only exposed one host. We are now exposing multiple hosts.
Within the VCAP_SERVICES JSON object we now provide a uris key at the same level as the uri key (which is what you currently use to connect). This new key contains an array of Elasticsearch hosts to connect to. You must modify your application to use these values. You may have to restage …
```
> Update elasticsearch config in initialiser

- production-app-manifest.yml
- production-worker-manifest.yml
- staging-app-manifest.yml
- staging-worker-manifest.yml
> **date: 20 February 2018 at 14:11**
> **subject: [paas-announce] Upcoming buildpack upgrades**
>
> Hi,
>
> We will be upgrading Cloud Foundry on or after 28th February 2018. We’re letting you know about the planned buildpack updates so you can make any changes to your application before the upgrade takes place. Please ensure that your version-pinning is compatible with versions cited in the planned releases. 
>
> ### ruby-buildpack
>
> New version: 1.7.8
>
> Release notes since the last buildpack change:
> https://github.com/cloudfoundry/ruby-buildpack/releases/tag/v1.7.11
> https://github.com/cloudfoundry/ruby-buildpack/releases/tag/v1.7.10
> https://github.com/cloudfoundry/ruby-buildpack/releases/tag/v1.7.9
>
> If you have any problems using the new versions in the buildpacks or …
> Upgrade Cloud Foundry buildpacks

- app/models/dataset.rb
- app/models/link.rb
- app/services/datasets_indexer_service.rb
- spec/models/dataset_spec.rb
- spec/models/link_spec.rb
- spec/services/datasets_indexer_service_spec.rb
The current strategy for generating short ids is nondeterministic. We want the same short id to be generated for a given dataset across multiple imports and environments.
This removes the behavior until we can revist it in due course.
A second PR will be raised to migrate the schema.
Closes #532 
See https://trello.com/c/VSLtBp7U and https://trello.com/c/YJEH4PC2
> Remove short id logic

- app/models/dataset.rb
- lib/tasks/import.rake
To make sure the state of the database is consistent with the state of the Find index, we delete all datasets and its dependents. That way, we avoid keeping datasets in the DB that have been removed from legacy since the last import.
> Remove datasets before importing

- .envrc
This adds the bin folder to your path so that running 'rake', 'rspec' etc will use the correct binstubs. This only applies if you have direnv installed and you give permission to allow it to use this configuration.
See https://direnv.net
> Add direnv configuration

- app/services/datasets_indexer_service.rb
- spec/services/datasets_indexer_service_spec.rb
This adds English mappings of certain fields. This will give us additional capability to use multi-fields is to analyze the same field in different ways for better relevance.
See https://www.elastic.co/guide/en/elasticsearch/reference/current/multifields.html#_multi_fields_with_multiple_analyzers
Trello https://trello.com/c/C6ZTU3gt & https://trello.com/c/EwF9fPiJ
> Add English field mappings to datasets index

- Gemfile.lock
Fixes the following warning:
```
/usr/local/var/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/iconv-1.0.4/lib/iconv/version.rb:1:
warning: constant ::Data is deprecated
```
> Fix iconv deprecation warning

- Gemfile.lock
2.2.0 has a security vulnerability. Bumping to patch
`bundle update loofah --patch`
> update Loofah gem from 2.2.0 -> 2.2.1

- production-worker-manifest.yml
The publish worker has more RAM on staging than on production, so this
PR increases the amount available for production.  This should hopefully
stop errors like
```
2018-04-04T12:48:12.98+0100 [API/0] OUT App instance exited with guid 2ba4e9ae-4553-4d61-9290-e9bd4e499089 
payload: {"instance"=>"68cc3fa5-fd58-4a56-7202-77e9", 
"index"=>0, 
"reason"=>"CRASHED", 
"exit_description"=>"APP/PROC/WEB: Exited with status 137 (out of memory)", 
"crash_count"=>1, 
"crash_timestamp"=>1522842492985954416, 
"version"=>"25a44111-b9ac-47f9-9767-27a3c1cbbad2"}
```
> Updates the RAM available to the publisher worker

- lib/tasks/search.rake
The previous implementation meant that the index name wouldn't always have the
correct environment appended to it.
> Update index_alias to use Rails.env

- scripts/replication.sh
After downloading the staging database and installing it, we need to 
tell the database that it is a development database (and not production)
as well as deleting an unused function to ensure we can run migrations.
The downside of this is that it's possible that when creating future
migrations, the schema.rb will attempt to include extensions that are
enabled on staging but may/may-not be installed locally.
> Make database usable after syncing

- db/migrate/2018041310444200_add_inspire_access_constraint_field.rb
- db/schema.rb
The access constraints from the INSPIRE metadata was missing, and so
this PR adds a migration to put it back as a text block.
Most constraints fall into one of three categories:
* Plain text
* A URL
* Paragraphs and paragraphs of text
Changes to the import/model will come in a separate PR with a rake task
for migrating just that data that is missing.
> Add the INSPIRE access constraints field to DB

- config/environments/production.rb
- config/environments/staging.rb
My experience of rails apps is that excessive logging also degrades
performance of the application server.
> Increase log level to avoid redundant spam

- app/models/dataset.rb
- app/models/licence.rb
- app/services/legacy/dataset_import_service.rb
- db/migrate/2018041810194100_add_new_licence_fields.rb
- db/schema.rb
- docs/arch/0001-licences.md
- spec/fixtures/legacy_dataset.json
- spec/fixtures/legacy_dataset_no_licence.json
- spec/services/legacy/dataset_import_service_spec.rb
This PR changes the handling of licences during import so that we have 4 new fields that we can use in bringing Find up to date.
The new fields (licence_code, licence_title, licence_url and licence_custom) will be set on import (either a full import or as a result of `rake import:single_legacy_dataset[environmental-pollution-incidents]`).  
The existing licence fields (licence and licence_other) can continue to be used until the migration is complete.
NB. This does not change the user-interface of Publish, this should be another PR.
https://trello.com/c/EwW9h6EU/12-some-licenses-missing-from-find-dataset-display-l
> Fix licence handling 

- app.json
The Heroku deployments have their environment set to staging, so we
(only) need to populate the VCAP_SERVICES variable to provide all of the
environment variables.
This is not ideal, and we should look at cleaning up the Heroku
environment variables, as well as improving the setup to include a
throwaway elasticsearch.
But this is just a quick fix to unblock the signon work.
> Remove redundant variables from Heroku schema

- lib/tasks/import.rake
Recent refactor means that the organisation and topic caches were
being refreshed on each run which is spectacularly inefficient.
> Speed up import by not asking for the same info on each dataset

- app/models/dataset.rb
- lib/tasks/delete.rake
Allows manual deleting of datasets by streaming a CSV into the rake task
which will process stdin as if it were a CSV.  Each row (containing a
legacy name or a UUID) will be used:
* Find the dataset
* Unindex the dataset
* Delete the dataset and related records
Usage:
```bash
echo "naptan" | rake delete:datasets
cat to_delete.csv | rake delete:datasets
```
This PR also adds to the dataset model, instructions for Rails on how to
process any dependent objects, in this case, delete them.  This means
any inspire metadata, and any links (docs or datafiles) associated with
the dataset
https://trello.com/c/ihbFAKwe/57-come-up-with-process-to-delete-datasets
> Add rake task to delete datasets (and associated records)

- Rakefile
- lib/tasks/lint.rake
To fix deploy failures:
```
rake aborted!
Don't know how to build task 'default' (see --tasks)
```
> Fix for missing default rake task

- app/views/layouts/_proposition_header.html.erb
This link appears to be a placeholder for a feature that was never
implemented. We should remove it to avoid confusion as it just links to
the tasks page.
https://trello.com/c/g66OcJcx/82-performance-tab-doesnt-do-anything
> Remove redundant Performance link in site nav

- app/models/dataset.rb
This is only required initially when the columns are removed, before the
app is restarted.
> Remove redundant dataset columns patch

- app/models/dataset.rb
The licence and licence_other fields are not used in Find anymore, they
have been replaced with 4 new fields that provide better coverage of the
licence metadata we require.  
These new fields are used during import
and we will require further work to change the fields used in the
Publish UI.  See
https://trello.com/c/mP0NcLrY/93-remove-licence-and-licenceother-fields
for more information.
> Do not index the old licence fields we don't use in Find

- app/services/legacy/dataset_import_service.rb
- spec/fixtures/legacy_dataset.json
- spec/services/legacy/dataset_import_service_spec.rb
When importing a legacy datafile, the importer was previously just using
the description field.  It should have been checking resource['name']
and only using resource['description'] as a fallback. This resulted in
lots of datasets having links called 'Resource locator' which is a
description of the link, rather than the name.
https://trello.com/c/b9VO8lOm/71-when-syncing-importing-we-end-up-with-links-that-have-no-name-when-they-should
> Choose the correct name for data files

- app/services/alias_updater_service.rb
- spec/services/alias_updater_service_spec.rb
https://trello.com/c/KsehMWJo/162-fix-reindexing-not-working-in-dev
This has been making https://trello.com/c/wQjbYbbv/50-last-updated-different-in-search-results-vs-dataset-page more difficult to complete.
The alias updater required an environment variable to specify the
current ES index to replace, which was really annoying to get manually.
Now the current index is determined automatically.
The alias updater used to remove the old alias link and serially and the
new one. A failure at this point would have caused Find to stop working.
Now the alias update (remove old link, add new link) is done atomically.
> Fix alias updater in dev and make it atomic

- production-app-manifest.yml
- staging-app-manifest.yml
This is causing unnecessary downtime e.g. for https://trello.com/c/Jy6YRdzO/157-make-orgs-work.
Looks like the default command is here: https://github.com/cloudfoundry/ruby-buildpack/blob/84e9b6ecda79b04c3dd02cd7c369566667c6a028/src/ruby/finalize/release.go
> Modify CF config to auto-migrate Postgres

- db/seeds.rb
Although a later PR will make Publish cope when a user has a non-mapped org, for now let's get it working for us as GDS users.
> Use GDS as seed org so PR apps work for us

- Procfile
Unfortunately the postdeploy script in app.json only runs when the app is first created. There's apparently no hook for something that runs every time it's deployed, apart from the start command.
> Make sure Heroku runs migrations every deploy

- app/views/datasets/licences/_licence_options.html.erb
- app/views/datasets/licences/edit.html.erb
- app/views/datasets/licences/new.html.erb
https://trello.com/c/XRQKhz80/158-add-additional-licence-fields
This adds the extra licence types, and also pulls the options into a partial so it can be shared between the create and edit flows.
> Add extra licence options

- db/migrate/20180503095708_add_user_study_org_mappings.rb
`update_attribute` takes a name, value pair not a hash - http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-update_attribute
> Fix org mappings for user study migration

- app/models/dataset.rb
- app/services/legacy/dataset_import_service.rb
- spec/models/dataset_spec.rb
- spec/services/legacy/dataset_import_service_spec.rb
For https://trello.com/c/wQjbYbbv/50-last-updated-different-in-search-results-vs-dataset-page
There are instances in Find Data where there is a mismatch between a dataset's "Last updated" timestamp that appears on the search results page and the timestamp that appears on the dataset's own page. We've agreed that the "Last updated" date should reflect the last time a datafile was modified, and if there are no datafiles present then the date that metadata was last modified should be used. In this PR we present a `public_updated_at` value to the Elasticsearch index which Find Data can use to display a "Last updated" date which satisfies the above logic.
> Send public_updated_at to elasticsearch

- app/views/datasets/datafiles/index.html.erb
- app/views/datasets/docs/index.html.erb
- app/views/datasets/show.html.erb
- spec/features/datafile_spec.rb
https://trello.com/c/Rw90WNqS/169-add-missing-cancel-buttons-for-all-wizard-edit-pages
Editing a dataset currently takes a similar journey to the initial
creation wizard, without the ability to cancel when you try to add a
datafile or doc; showing 'Skip this step' in the context of adding a
datafile or doc also doesn't make sense. This is fixed by changing the
dataset page to remove the 'Add Data' link for datafiles and docs. A
user can still add a new datafile or doc via the 'Change' button, which
takes them to a list of all datafiles of docs with a link to add a new
one. Seeing 'Skip this step' in this context makes more sense because of
the multi-click journey to get to the page.
Clicking 'Save and continue' after a adding a datafile currently prompts
the user to add a doc unless the …
> Improve user journeys for editing a dataset

- app/services/legacy/api_service.rb
In some cases the LEGACY_HOST ends with a /, so just concatenating the
path doesn't work.
> Fixes an error if LEGACY_HOST ends with a /

- app.json
These vars are only required when GDS SSO is configured to use the
'real' strategy, so they're optional but a little tricky to find.
> Document optional vars for using signon

- app/services/legacy/api_service.rb
- lib/tasks/import.rake
As we encounter issues with the synchronisation, we occassionally get
publishers running their harvester and ending up with 1400 datasets that
have not synced to publish, and fall outside the window within which we
check for changes.
Running this task, with the short name of an organisation, and a boolean
will:
* Delete all the datasets for the organisation if the boolean is "true"
* Re-import all of the datasets for the organisation from the legacy API
There is no transaction, if the container runs out of memory half way
through, you need to run it again! This should only be used in dire
emergencies.
> Rake task to reset all of the datasets for a single organisation

- app.json
https://trello.com/b/a30DSRUe/dgu-q1-doing
Rather than specifying a custom URI for signon, PLEK expects a variable
called GOVUK_APP_DOMAIN to be set, which it will then use to build the
signon URI and any other URIs.
> Replace PLEK URI override with GOVUK app domain

- app/services/datasets_indexer_service.rb
When we reindex the entire database, it is very slow.  By pre-fetching
records (ActiveRecord changes the includes call into an eager_load
because of the where clause) less time is spent querying the database.
By changing the batch size `rake search:reindex[100]` to something 
larger than the default (50) it can be increased significantly. A batch size 
of 500, although using nearly 400Mb of RAM will complete in about 4m.
A batch size of 100 takes about 5 minutes.
> Speed up indexing by prefetching records

- lib/validators/url_validator.rb
- spec/validators/url_validator_spec.rb
The validator was not correctly handling the cases where there was a
network level failure (broken read/write, dns failure etc).
> Fixes urlvalidator to handle network errors

- lib/validators/url_validator.rb
- spec/validators/url_validator_spec.rb
RestClient doesn't like making requests with non-encoded strings, and so
this PR will encode the string, if it is not already. This stops the
validation complaining about URLs the user has given that may contain
spaces.
Also adds ftp to the list of allowed URLs.
> Fixes some problems with non-perfectly-formed URLs

- app/models/dataset.rb
- spec/factories/dataset.rb
- spec/models/dataset_spec.rb
https://trello.com/c/SkQ9KxWf/139-show-availability-of-datasets-in-search-results
Previously Find would try to infer the dataset released status by using
the count of links. However, the nested link documents are not returned
for certain queries, meaning the released status could not be
determined. Exporting the attribute as a static value solves this
problem.
> Export dataset released status to ES

- .travis.yml
- production-app-manifest.yml
- production-worker-manifest.yml
- scripts/deploy-production.sh
The application name has changed so that it conforms to conventions needed for production to staging sign-on sync.
See https://trello.com/c/mBViuo1y
> Update references to production publish application¬

- production-worker-manifest.yml
- staging-worker-manifest.yml
https://trello.com/c/SoMECEgx/311-try-and-sort-out-the-crashing-issues-with-the-sync-worker
CloudFoundry uses Docker to launch containers and constrains their heap
memory to a specified number, within the quota of the plan chosen. This
conflicts with Ruby's GC, which cannot be tuned to keep reserved memory
within a limit - it instead works in terms of object counts.
As it's not possible to stop the issue entirely, we can at least reduce
it's frequency by giving the worker a little more memory.
> Increase worker memory limit on staging/production

- app/controllers/datasets/licences_controller.rb
- app/models/dataset.rb
- app/services/legacy/dataset_import_service.rb
- app/views/datasets/licences/_licence_options.html.erb
- app/views/datasets/show.html.erb
- db/migrate/20180605144307_remove_legacy_licence_fields.rb
- db/schema.rb
- spec/factories/dataset.rb
- spec/features/create_dataset_spec.rb
- spec/features/edit_dataset_spec.rb
- spec/models/dataset_spec.rb
- spec/services/legacy/dataset_import_service_spec.rb
- spec/support/dataset_helper.rb
https://trello.com/c/IzJCX5UY/337-remove-licence-and-licenceother-fields-from-publish
This fields are replaced with licence_code, licence_title, etc. As prt
of removing these fields, it became clear that the form element to
populate the licence_other field was broken. As the field no longer
exists, it made more sense to remove the redundant code than try and fix
the broken feature, as leaving a reference to licence_other would be
more confusing.
> Remove unused licence and licence_other fields

- app/models/dataset.rb
- app/views/manage/_base.html.erb
- spec/controllers/datasets_controller_spec.rb
https://trello.com/c/DFd1msUC/347-remove-backend-readonly-validation-for-harvested-datasets
Datasets previously had a read_only validation that was in conflict with
the CKAN sync, as this should be able to update harvested datasets.
It would be difficult to use validation contexts to work around this, as
there are many that could apply and only one (sync) that does not.
Because harvested datasets are not shown to the user, it should be OK to
remove this backend protection as it's unlikely to ever be used.
> Remove readonly validation for harvested datasets

- app/controllers/datasets/frequencies_controller.rb
- app/controllers/datasets/licences_controller.rb
- app/controllers/datasets/topics_controller.rb
- app/models/dataset.rb
- app/views/datasets/licences/new.html.erb
- spec/features/create_dataset_spec.rb
- spec/models/dataset_spec.rb
https://trello.com/c/JFfTjKko/338-only-validate-licence-frequency-and-topic-when-using-the-wizard
Previously dataset validations would partially occur when the dataset
was published. This would interact badly with the CKAN sync such that
all validations were disabled.
The validations now scoped in contexts specific to the page of the
dataset form they are required on. This meant it was necessary to remove
the 'Skip this step' option for licences.
Some of the controllers were dealing with form parameters in different
ways. In order to ensure the validations were consistent, some of the
controllers have been changed to have the same structure.
> Scope dataset validation to only happen in wizard

- app/models/dataset.rb
- db/migrate/20180607110440_remove_unused_dataset_fields.rb
- db/migrate/20180607110616_remove_unused_link_fields.rb
- db/schema.rb
- spec/features/create_dataset_spec.rb
- spec/features/datafile_spec.rb
- spec/features/edit_dataset_spec.rb
- spec/features/harvested_dataset_spec.rb
https://trello.com/c/g07wP2X9/325-remove-old-sync-code-after-replacing-it-with-the-new-sync-code
These aren't used anywhere in the app and should be removed to reduce
confusion when trying to inspect these types of record.
> Remove unused dataset and link properties

- app/controllers/datasets_controller.rb
- app/models/dataset.rb
- app/views/datasets/show.html.erb
- config/locales/en.yml
- spec/features/edit_dataset_spec.rb
- spec/models/dataset_spec.rb
We should be able to delete a published dataset, so the logic preventing
this has been removed, bringing the behaviour in-line with CKAN sync; a
further piece of work will be necessary to propagate deletions to ES.
The logic for setting the published_date an last_updated_at timestamps
before publishing is also invalid as it implies these timestamps are
required to publish a dataset; in reality, they are not used in Find.
> Remove invalid publishing logic for datasets

- app/workers/ckan/v26/import_worker.rb
- spec/features/ckan_v26_import_spec.rb
GOV.UK Sidekiq injects additional context when a Sidekiq job is retried.
In order to ensure the worker can support retry functionality, we need
to support an extra context argument. There seems to be a bug whereby
GOV.UK Sidekiq appends the same context argument every time the job is
retried (instead of replacing the old one) - have raised an issue.
> Support retry for CKAN import worker

- app/models/dataset.rb
- app/services/datasets_indexer_service.rb
- spec/features/ckan_v26_import_spec.rb
- spec/features/ckan_v26_sync_spec.rb
- spec/features/dataset_publish_spec.rb
- spec/support/es_helper.rb
https://trello.com/c/fzYhwLSf/369-use-the-uuid-to-identify-a-dataset-in-elasticsearch-not-a-random-number
The UUID for a dataset should be used everywhere to uniquely identify a
dataset, preventing duplicates and simplifying maintenance and
development tasks where it's necessary to query the ES index directly.
> Switch to using UUID for ES unique IDs

- lib/tasks/search.rake
https://trello.com/c/fzYhwLSf/369-use-the-uuid-to-identify-a-dataset-in-elasticsearch-not-a-random-number
> Allow ENV override when reindexing

- config/sidekiq.yml
Takes away the Beta Update Worker so that we can manually rebuild the search index before switching to CKAN::V26::SyncWorker
> Disable Beta Update Worker in production

- config/sidekiq.yml
We don't want it running in development or test. Also, it turns out our
Heroku environment doesn't have enough resources to run the sync job.
> Restrict CKAN sync to only run on staging/prod

- app/models/ckan/v26/ckan_org.rb
- app/services/ckan/v26/ckan_org_differ.rb
- app/services/ckan/v26/organisation_mapper.rb
- app/services/ckan/v26/organisation_updater.rb
- app/workers/ckan/v26/ckan_org_import_worker.rb
- app/workers/ckan/v26/ckan_org_sync_worker.rb
- lib/ckan/modules/url_builder.rb
- lib/ckan/v26/client.rb
- spec/factories/ckan_v26_ckan_org.rb
- spec/features/ckan_v26_ckan_org_sync_spec.rb
- spec/fixtures/files/ckan/v26/list_organization.json
- spec/fixtures/files/ckan/v26/show_organization_create.json
- spec/fixtures/files/ckan/v26/show_organization_update.json
- spec/services/ckan/v26/organisation_mapper_spec.rb
https://trello.com/c/USyQ4NBd/389-sync-a-single-organisation-to-the-database-using-the-ckan-api
The naming conflict between the local 'Organisation' model and the CKAN
'Organization' model is resolved by using 'CKANOrg' to refer to the
latter. Any deletions are scoped to organisations that do not have a
govuk_content_id, as this implies they are accessible in this app.
> Add worker to sync CKAN orgs with the local DB

- db/migrate/20180618155007_remove_redundant_dataset_columns.rb
https://trello.com/c/g07wP2X9/325-remove-old-sync-code-after-replacing-it-with-the-new-sync-code
These columns are not used in Publish or Find and can now be safely
removed.
> Remove redundant dataset columns

- app/models/dataset.rb
- app/workers/ckan/v26/ckan_org_sync_worker.rb
https://trello.com/c/6w4BSyGg/390-sync-a-single-organisation-to-find-using-the-ckan-api
It's possible for a dataset to be unpublished but not deleted as these
operations span multiple databases. We can safely catch a NotFound error
when unpublishing because the operation becomes a no-op; this should
only occur when a previous batch delete has failed and does not indicate
a consistency issue in general, provided the sync workers run regularly.
> Ignore missing datasets when unpublishing

- doc/adr/0002-signon.md
https://trello.com/c/3r6gUCTG/405-rewrite-the-dgu-developer-docs
A user is now assigned to an organisation by lookup using the
govuk_content_id attribute, if one exists. The ADR should be updated to
avoid confusion with the original behaviour.
> Update the Signon ADR to reflect the app behaviour

- app/models/dataset.rb
- spec/models/dataset_spec.rb
https://trello.com/c/gVCoFinx/420-investigate-sync-issues
We should ensure that we receive a 'success' response from ES when
performing operations, as it looks like these sometimes fail after
seeing discrepancies between the number of documents in the local DB and
in ES, despite there being no indexing issues when manually publishing.
> Ensure ES operations succeed for index/delete_doc

- app/models/dataset.rb
- spec/factories/dataset.rb
- spec/factories/inspire_dataset.rb
- spec/features/ckan_v26_package_import_spec.rb
- spec/features/dataset_publish_spec.rb
https://trello.com/c/vEj1dI9y/339-last-updated-field-doesnt-represent-the-real-date-that-some-data-fields-were-updated
The INSPIRE reference dates are a better indicator of recency for a
dataset, where available. If a dataset has INSPIRE metadata, we will use
the maximum of its reference dates as the dataset public_updated_at,
provided these dates are valid (day, month, year).
From user examples we can see that, while 'revision' is commonly the
right reference date to use, sometimes this is not available but another
reference field like 'published' can serve as a suitable indiactor of
recency; to avoid complex logic, we'll start by maxing over them all.
> Use the INSPIRE ref date for public_updated_at

- db/migrate/20180502153341_map_gds_content_id_from_govuk.rb
https://trello.com/c/VvaTibq9/435-fix-publish-migrations-out-of-order
For some reason the original name/UUID for GDS was incorrect.
> Fix UUID for GDS Org to match CKAN

- production-app-manifest.yml
- staging-app-manifest.yml
This application no longer requires metric collection by the
GDS prometheus, as implemented by
https://github.com/alphagov/datagovuk_publish/pull/684
This commit removes the PaaS service bind so that Prometheus
will not try and collect metrics as intended.
> Do not bind GDS prometheus to the PaaS app

- config/initializers/elasticsearch.rb
- production-app-manifest.yml
- production-worker-manifest.yml
- staging-app-manifest.yml
- staging-worker-manifest.yml
The PaaS is switching from IBM Compose to Aiven.  There are some changes to the configuration format, so this isn't just a straight change to the manifest.
---
The change has already been applied to the running DGU instances.  In addition to this PR, there was some devopsing around creating the new backing service (hence the new names) and reindexing everything.
---
[Trello card](https://trello.com/c/uQVcQkJ0/364-move-dgu-paas-elasticsearch)
> Switch to new elasticsearch

- app/services/ckan/v26/link_updater.rb
- spec/features/ckan_v26_package_import_spec.rb
https://trello.com/c/wgthCJFX/236-fix-datafile-updates-not-working
The original design for sync required that all imported datasets should
be editable within the new publishing app, which meant running
validations on all the models on save. While this raised no initial
issues, it turns out that only once a datafile has been saved do the
datafile validations start to apply i.e. first save works, second fails.
As the new publish app is no longer a going concern, it's no longer
sensible to enforce its arbitrary validations and instead disable them
where the tests show this is required. This is the case for datafiles,
where a constraint on the transient year attribute prevented updates.
> Ignore validations for links (and others)

- config/environments/staging.rb
The CKAN staging server has been turned off. Since the staging url no
longer resolves, running staging publish on the Paas now results in
errors being thrown when the Sidkekiq workers try to sync data from the
staging CKAN. Setting this url to the live version of CKAN should stop
this error occurring. This does mean that we will be syncing the live
data to both staging and production versions hosted on the Paas.
> Set staging ckan base url to data.gov.uk

- README.md
These instructions explain how GOV.UK developers can run Publish (including the sync) on their local machine
> Add instructions for running Publish on a Mac

- app/services/ckan/v26/package_differ.rb
There have been a large number of CKAN::V26::Depaginator::DeletionTooLargeError exceptions recently.  This is preventing the sync from CKAN to Publish from running correctly.  This was happening because we were comparing the total number of datasets against the new number of datasets, rather than just comparing the published datasets against the new number of datasets.
> Only count deletions against the number of published documents

- app/models/dataset.rb
If a dataset has already been removed from the index (e.g. by a concurrent worker), `delete_document` will return a 404 error.  This has resulted in a large number of errors being sent to Sentry.  Adding `ignore: 404` will stop this error where the dataset has already been deleted.
Trello card: https://trello.com/c/5GaHfYts/107-how-might-we-send-fewer-errors-to-sentry-from-publish
> Ignore datasets that have already been deleted from the index

- app/models/dataset.rb
- spec/features/dataset_publish_spec.rb
https://govuk.zendesk.com/agent/tickets/3539916
Previously we calculated the public_updated_at field for a dataset based
on the first available timestamp in the list of things to try. This
changes the way we calculate this field as part of the publish payload,
so that we try to get the latest timestamp out of the ones available.
> [REQUIRES REINDEX] Revamp the way we calculate public_updated_at

- config/environments/staging.rb
This is temporarily pointing to integration, until we have some data on staging.
> Update URL of CKAN in staging

- lib/ckan/v26/client.rb
Previously CKAN returned only datasets.  Now it returns packages (datasets and harvesters).  This filters that back down to datasets only.
> Update path for CKAN dataset search endpoint

- production-app-manifest.yml
- production-worker-manifest.yml
- staging-app-manifest.yml
- staging-worker-manifest.yml
As ES 5 will no longer be supported, a new ES 6 service has been deployed to replace it.
This PR also contains code updates to reorder production services like staging to make it easier to maintain the manifests
> Update services to use elasticsearch 6 service

- app/models/healthcheck/recurring_jobs/ckan_org_sync.rb
- config/routes.rb
- spec/integration/healthcheck_spec.rb
- spec/models/healthcheck/recurring_jobs/ckan_org_sync_spec.rb
- spec/models/healthcheck/recurring_jobs/package_sync_spec.rb
The CKANOrgSyncWorker is a recurring job that runs once every 24
hours. We currently don't have any alerts in place to monitor it's
running successfully.
The `WARNING_DELAY` and `CRITICAL_DELAY` has been set based 
on it's [Sidekiq retry number](https://github.com/alphagov/datagovuk_publish/blob/master/app/workers/ckan/v26/ckan_org_sync_worker.rb#L5) and by referring to the automatic job retry table
in the [wiki](https://github.com/mperham/sidekiq/wiki/Error-Handling#automatic-job-retry)
Trello card: https://trello.com/c/ba8SOqEM/960-add-an-icinga-alert-to-notify-us-if-any-of-the-scheduled-dgu-sync-jobs-are-disabled
> Add healthcheck for CKANOrgSyncWorker

- lib/tasks/fix_existing_organogram_filenames.rake
- lib/tasks/update_organogram_filenames.rb
- spec/lib/tasks/update_organogram_filenames_spec.rb
It seems like changes to the ckan database and solr index are not picked up by Publish automatically, so in order to force it to pick up the filename fixes in this card - https://trello.com/c/5KrmZ1tb/1025-fix-bug-to-show-visualisation-on-junior-post-organograms, we need to run a one-off script to update the filenames in the Publish DB, then we just reindex elasticsearch and the filenames should be updated.
The input to the process was generated by a run of this script on the appropriate environment - 
https://github.com/alphagov/ckanext-datagovuk/blob/master/bin/python_scripts/fix_organograms_s3_filenames.py
> Fix organogram filenames

- lib/tasks/update_organogram_filenames.rb
- spec/lib/tasks/update_organogram_filenames_spec.rb
This improvement means we are only searching for specific links,
rather than looping through all of them. We discovered this when
testing on staging where it caused a memory issue on the VM and
the task gets killed.
Trello card: https://trello.com/c/5KrmZ1tb/1025-fix-bug-to-show-visualisation-on-junior-post-organograms
> Add a filter to the links to process in the script

- app/workers/ckan/v26/package_import_worker.rb
In staging, the CKAN postgres database is synced from production every day. When this was set up we made a decision to not sync Solr because it's a new technology on GOV.UK, it takes 3 days to reindex and it would involve writing custom sync code for Solr.
When accessing the CKAN API the `/api/3/search/dataset` endpoint is backed by the data in Solr which means that it returns results for datasets which have subsequently been removed (during the data sync process if the dataset is removed in production). The import worker then tries to access more information about those datasets but that endpoint (which is now backed by Postgres) returns a 404 error.
In production this tells us about a real problem in our system (Solr is out of sync with Postgres) but in staging it's not very useful, and …
> Ignore 404 errors in non-production environments

- .rubocop.yml
- app/controllers/application_controller.rb
- app/controllers/datasets/licences_controller.rb
- app/controllers/datasets/locations_controller.rb
- app/helpers/application_helper.rb
- app/models/healthcheck/recurring_jobs/ckan_org_sync.rb
- app/models/healthcheck/recurring_jobs/package_sync.rb
- app/models/topic.rb
- app/services/index_deletion_service.rb
- config/application.rb
- config/environments/development.rb
- config/initializers/elasticsearch.rb
- lib/ckan/v26/depaginator.rb
- lib/tasks/search.rake
- spec/features/ckan_v26_package_sync_spec.rb
- spec/features/dataset_create_spec.rb
- spec/rails_helper.rb
In order to fix duplicate datasets we need to remove just under 1500 datasets, the `MAX_DELETIONS` limit prevented it from running so to get those duplicates removed we need to temporarily up the limit.
> Up the max deletions to fix duplicate datasets

- lib/ckan/v26/depaginator.rb
The limit was raised to 1500 in order to remove duplicate datasets, but now that they have been removed its a good idea to restore the original value as a fail safe.
> Set MAX_DELETIONS limit to 100

- README.md
Commands will not run without starting the shell up in the correct build environment, so it needs to be run each time if we want to do things like re-index elasticsearch.
> Update README with some PaaS info

- production-app-manifest.yml
- staging-app-manifest.yml
Similar to https://github.com/alphagov/datagovuk_publish/pull/641/commits
we have been experiencing crashing package sync jobs which turned out
to be due to memory limits throughout the PackageDiffer process.
A longer term fix may be to batch this process.
> Increase app memory on staging and production

- lib/ckan/v26/depaginator.rb
Reverts alphagov/datagovuk_publish#805
Temporarily raise MAX DELETIONS to remove back log that is currently raising lots of errors:
https://sentry.io/organizations/govuk/issues/1398589208/?project=275566&query=is%3Aunresolved
> Revert "Set MAX_DELETIONS limit to 100"

- app/assets/stylesheets/application.css.scss
- app/assets/stylesheets/components.scss
- app/assets/stylesheets/govuk-overrides.scss
- app/views/manage/manage_own.html.erb
This app use the `govuk_frontend_toolkit` for its styles,
but recently has been having trouble finding variables such as
$link-colour, which is blocking deployments.
As we don't need to access Publish via the frontend we can
remove references to these variables in the affected Sass files.
Trello card: https://trello.com/c/LhIWTWKQ/1693-3-remove-dependency-which-is-blocking-deployment-of-dgu-publish
> Remove style variables

- scripts/deploy-production.sh
- scripts/deploy-staging.sh
There's no need to deploy the frontend part of Publish as we only need the workers to synchronise CKAN solr and DGU elasticsearch.
> Don't deploy the frontend as its not in use

- .travis.yml
Had thought it was removed when we took out the deployment from the deploy scripts but we also need to remove it from the travis file
> Remove frontend deployment from travis

- lib/ckan/v26/depaginator.rb
Reverts the revert here -
https://github.com/alphagov/datagovuk_publish/pull/890/files.
This threshold was changed to 1500 to allow a legitimate mass deletion
of datasets from Barnet Council, however we now need to change this back
to preserve find from deleting datasets when there is a miscommunication
between it and CKAN.
Related incident:
https://docs.google.com/document/d/13WprBbnTbef4gisSa0EoYpXjP_ZRmujoYAHx3o_DlLQ/edit#
> Lower threshold of MAX_DELETIONS limit

- .travis.yml
- Rakefile
- lib/tasks/lint.rake
- Now we don't use `govuk-lint` to wrap RuboCop, we _could_ switch this
to run `bundle exec rubocop`, but that's not very useful as it hides
the directories that it operates on, and we're trying to move away
from wrappers.
- Instead, I think we can leave people to run `bundle exec rubocop` on
their own - it's less typing than `bundle exec rake lint` and
`rubocop --help` works for options.
- Now there's no `lint` Rake task, we have to run `rubocop` on CI
directly.
https://trello.com/c/IEUuFOVa/129-remove-the-lint-rake-task-from-apps-that-have-it as part of the developer tooling group
> Remove `lint` Rake task

- .rubocop.yml
- app/controllers/application_controller.rb
- app/models/dataset.rb
- db/seeds.rb
- lib/ckan/v26/depaginator.rb
- spec/features/dataset_edit_spec.rb
- spec/rails_helper.rb
- spec/services/alias_updater_service_spec.rb
The `rubocop-govuk` gem has moved on a bit since these excludes in
`.rubocop.yml` were written. As part of standardizing our RuboCop
configs across all the repos - because otherwise what's the point of
having a set of rules? - this removes all the special excludes and
fixes the new failures.
> rubocop: Remove redundant configs

- Dockerfile
- bin/setup-docker.sh
- config/database.yml
- config/elasticsearch.yml
- config/environments/development.rb
- config/redis.yml
- config/sidekiq.yml
In order to get Publish to run in the alphgov/docker-ckan
dev stack it is necessary to add these files and add in environment vars for
redis and ckan hosts so that it is still possible to run Publish as a standalone app.
> Add Dockerfile, setup-docker and docker environment

- Dockerfile
- app/services/ckan/v26/package_differ.rb
- config/environments/production.rb
- config/environments/staging.rb
- config/environments/test.rb
- lib/ckan/v26/depaginator.rb
- production-app-manifest.yml
- production-worker-manifest.yml
- spec/features/ckan_v26_package_sync_spec.rb
- spec/fixtures/files/ckan/v26/search_dataset_p1.json
- spec/fixtures/files/ckan/v26/search_dataset_p2.json
- staging-app-manifest.yml
- staging-worker-manifest.yml
Filter out test publisher to prevent it from being harvested and pushed to the data.gov.uk Find frontend. 
Also update the buildpack for deployment as we upgraded to Ruby 2.6.6
https://trello.com/c/bi425MX0/135-block-data-from-test-publisher-on-ckan-from-reaching-dgu-find
> Filter out test publisher

- config/environments/development.rb
`test_publisher` config setting was missed off the development config setting causing the app to break, so adding it in will enable the sidekiq workers to run.
> Add test_publisher config to dev environment

- Rakefile
- spec/lib/tasks/update_organogram_filenames_spec.rb
Rubocop is not available when deploying to staging or production so don't run the require rubocop or run the rake task if it isn't available.
> Only run rubocop under development or test

- bin/setup-docker.sh
Before running sidekiq the added code will check that CKAN is running, otherwise sidekiq will flood the console with errors .
> Update setup-docker to check that CKAN is running

- lib/ckan/v26/depaginator.rb
In order to run the CKAN functional tests, some existing test data had to be removed which may have caused the MAX_DELETIONS threshold to be hit, so temporarily increase it to 500 to allow test data to be removed.
> Temporarily increase max deletions to 500

- lib/ckan/v26/depaginator.rb
Add in the definition for DeletionTooLargeError as it is throwing errors and up the limit to 1000 as it seems like there are lots of deletions.
> Add DeletionTooLargeError and up MAX_DELETIONS

- lib/ckan/v26/depaginator.rb
Up the MAX_DELETIONS to 10,000 as it seems like the solr reindex / db rebuild may have caused the number of datasets to be changed.
> Temp up the MAX DELETIONS to 10000

- config/initializers/inflections.rb
This was added in d021903 to namespace certain controllers but this no longer applies. However it has the unfortunate side-effect of breaking the gds-sso gem's namespacing for the user controller because it uses the title-case variant 'Api::UsersController'. When the zeitwerk autoloader sees the acronym and the api directory it auto generates the module 'API' but then runs into problems trying to generate the controller and raises a NameError for the constant 'Api'. We can remove the acronym as there is no longer anything namespaced under 'API' within this app.
> Remove acronym inflection for API

- Gemfile
- Gemfile.lock
- lib/ckan/v26/depaginator.rb
These are the necessary changes for Ruby 2.7.1
Since there is a script to change all apps' versions automatically, leaving the Ruby version at 2.6.6 in this PR.
There are some deprecation warnings coming from the Kaminari gem, but there is a note in the Gemfile not to update it unless ElasticSearch is updated, which seems like a separate issue
> Upgrade to ruby 2.7.1

- production-worker-manifest.yml
- staging-worker-manifest.yml
Use Postgres 12 and not Postgres 9.5 is being withdrawn from paas because its no longer being supported.
> Use postgres 12 

- db/seeds.rb
Add performance platform topics so that they can be found easily on the Find app.
https://trello.com/c/NCq4ylTw/2367-3-add-topics-on-dgu-for-performance-platform
> Add performance platform topics

- config/production/nginx.conf
- config/staging/nginx.ckan.conf
We received a ticket (https://govuk.zendesk.com/agent/tickets/4707289) in which the user described seeing an Nginx error message '413 Request Entity Too Large' when uploading a 30mb file. I was able to reproduce this error.
> Double allowed upload size to 50 MB

- app/services/ckan/v26/link_mapper.rb
- spec/factories/ckan_v26_resource.rb
- spec/services/ckan/v26/link_mapper_spec.rb
We are currently assigning the `created` date from CKAN to both the `created_at` and `updated_at` values for links in the frontend of data.gov.uk.
This leads to a situation where publishers update data in CKAN, but the updated date does not change on DGU Find as it remains fixed on the creation date.
Making this change to correctly set the updated date.
[Zendesk ticket](https://govuk.zendesk.com/agent/tickets/4751177)
> Correctly assign updated date to links

- app/services/ckan/v26/link_mapper.rb
- spec/fixtures/files/ckan/v26/package_show_update.json
- spec/services/ckan/v26/link_mapper_spec.rb
Updates how the `build_type` interprets CKAN API responses when looking for supporting documents.
Missed update from the most recent CKAN upgrade. Detailed explanation from Bruce via [this zendesk ticket](https://govuk.zendesk.com/agent/tickets/4770524):
>It appears the API response from CKAN is different to what we're using to import to DGU.  I remember this being flagged as a post-CKAN upgrade issue, but presumably never got fixed.
>
>Example API response (see value for `resource-type` for each link, it shows whether it should be a dataset or supporting link):
>https://ckan.publishing.service.gov.uk/api/action/package_show?id=d0be1ed2-9907-4ec4-b552-c048f6aec16a
>
>What we're expecting:
>https://github.com/alphagov/datagovuk_publish/blob/30229772be42b054a85c97037c4eaaaeafa16ee0/app/servi …
> Update build_type method to use correct API

- app/lib/ckan/v26/depaginator.rb
Expecting just over 4000 deletions due to duplicate datasets being removed. After the duplicate datasets have been removed MAX_DELETIONS should be set back to 100.
https://trello.com/c/5LSihxlF/1139-investigate-and-fix-duplicate-datasets
> Temporarily update MAX_DELETIONS to 4100

- app/lib/ckan/v26/depaginator.rb
Reverts alphagov/datagovuk_publish#1163
Now that the deletions have been applied we can revert back to 100 max deletions
https://trello.com/c/5LSihxlF/1139-investigate-and-fix-duplicate-datasets
> Revert "Temporarily update MAX_DELETIONS to 4100"

- integration-worker-manifest.yml
- production-worker-manifest.yml
- staging-worker-manifest.yml
Redis 3 is being withdrawn from PaaS, so upgrade to redis 6
> Update manifests to use redis 6

- app/lib/ckan/v26/depaginator.rb
Staging stack is stuck as there are a large number of deletions required to keep Find and CKAN in sync so allow the deletions for Staging.
> Increase MAX_DELETIONS to 16495

- app/lib/ckan/v26/depaginator.rb
Reverts alphagov/datagovuk_publish#1204
Now that the deletions have completed on Staging revert back to the 100 deletions limit
> Revert "Increase MAX_DELETIONS to 16495"

- integration-worker-manifest.yml
- production-worker-manifest.yml
- staging-worker-manifest.yml
Ruby 3.2.2 isn't available in ruby-buildpack 1.9.3 so upgrade to 1.10.4
> Update ruby buildpack to 1.10.4 for ruby 3.2.2

- .github/workflows/create-pr.yaml
- docker/create-pr.sh
Description:
- Fixes the create-pr action by providing the correct path for create-pr.sh
- Only one app in directory so can remove the iterator
> Fix create PR action

- config/redis.yml
Kubernetes cluster doesn't have VCAP_SERVICES env var, just use the REDIS_HOST env var if available.
> Update redis host k8s

- .github/workflows/build-image-on-tags.yaml
- docker/build-image.sh
Description:
- Adds a GitHub Action to build the docker image but tagged
- Use 'k' instead of 'v' to avoid clashing with the existing docker images as this isn't ready to release without testing yet
> Add build-image-on-tags GitHub action

- .github/workflows/build-image-on-tags.yaml
- .github/workflows/create-pr-on-tags.yaml
Description:
- Adds a GitHub action which opens a PR against the govuk-dgu-charts repository for the datagovuk_publish once build-image-on-tags is completed
> Add create-pr-on-tags action

- .github/workflows/create-pr-on-tags.yaml
Description:
- Currently the create-pr-on-tags action uses the latest 'v' version due to git tag. Changing this to `git tag -l "k*"` will let us use the `k` version
- Future PR will revert this back to `v` once we are satisfied the pipeline is working correctly
> Fix create-pr-on-tags to use k tag not v

- app/models/ckan/v26/package.rb
- app/services/ckan/v26/inspire_mapper.rb
- spec/factories/ckan_v26_package.rb
- spec/services/ckan/v26/inspire_mapper_spec.rb
Some of the records captured from CKAN have time info which elasticsearch will reject.
> metadata_date should be in the form YYYY-MM-DD

- app/models/dataset.rb
- spec/models/dataset_spec.rb
Most of the errors coming from the elasticsearch indexing are coming from bad data which we have little control over as it is managed by external publishers, so log the errors rather than raising them to stop Sentry being flooded by these validation errors.
> Log errors coming from elasticsearch indexing

- README.md
The deployment guidance was duplicated (and more comprehensive) elsewhere, so this removes it from here and provides a link instead.
> Link to deployment docs elsewhere

- app/lib/ckan/v26/depaginator.rb
Allow max deletions to increase to 8000 to fix sync dataset sync issues on Integration and Staging.
> Increase max deletions to 8000

- app/lib/ckan/v26/depaginator.rb
Delete 15647 records as one of the publishers wishes to remove all their datasets.
> Update MAX_SIZE deletion to 15647

- .github/workflows/build-image.yaml
- app/services/ckan/v26/inspire_mapper.rb
- docker/build-image.sh
The harvest object id from the harvest element in the CKAN response is more up to date than the harvest object id from extras so use that instead.
Also add in a way to build a dev image for debugging on the deployed cluster.
> Fix inspire mapper harvest object

- app/workers/ckan/v26/package_import_worker.rb
The publish worker is throwing errors when retrying a dead job so don't retry for package imports.
> Do not retry for package import workers as it is run every 10 minutes anyway

- app/workers/ckan/v26/package_import_worker.rb
The ID doesn't appear to exist in the publish database, and as Publish will soon be removed from the stack just ignore errors from this ID
> Ignore package import errors from 85f9f30b-4e09-4968-b24d-d4c68f17b9af
